Repository apollographql/rover, pull requests merged in 2020-10, with the labels that each got.

#58 tests(rover): cleans up invalid API key tests
  Cargo.lock
  Cargo.toml
  src/command/config/api_key.rs
  tests/profile.rs
Labels: operations - maintenance

#23 schema get
  Cargo.lock
  Cargo.toml
  crates/rover-client/Cargo.toml
  crates/rover-client/schema.graphql
  crates/rover-client/src/blocking/client.rs
  crates/rover-client/src/blocking/mod.rs
  crates/rover-client/src/error.rs
  crates/rover-client/src/headers.rs
  crates/rover-client/src/lib.rs
  crates/rover-client/src/query/mod.rs
  crates/rover-client/src/query/schema/get.graphql
  crates/rover-client/src/query/schema/get.rs
  crates/rover-client/src/query/schema/mod.rs
  src/cli.rs
  src/command/mod.rs
  src/command/schema/fetch.rs
  src/command/schema/mod.rs
  tests/config/api_key.rs
  tests/config/mod.rs
  tests/config/profile.rs
  tests/main.rs
  tests/schema/fetch.rs
  tests/schema/mod.rs
Labels: changelog - feature

#52 tests telemetry reporting
  Cargo.lock
  crates/sputnik/Cargo.toml
  crates/sputnik/src/report.rs
  crates/sputnik/src/session.rs
  src/telemetry.rs
Labels: operations - maintenance, status - needs review

#46 report anonymous usage data (telemetry)
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  crates/houston/Cargo.toml
  crates/houston/src/error.rs
  crates/houston/src/home.rs
  crates/houston/src/lib.rs
  crates/houston/src/profile/mod.rs
  crates/houston/src/profile/sensitive.rs
  crates/sputnik/Cargo.toml
  crates/sputnik/README.md
  crates/sputnik/src/error.rs
  crates/sputnik/src/lib.rs
  crates/sputnik/src/report.rs
  crates/sputnik/src/session.rs
  docs/gatsby-config.js
  docs/source/contributing/project-structure.md
  docs/source/privacy/index.md
  docs/source/usage/config/environment-variables.md
  src/bin/rover.rs
  src/cli.rs
  src/command/config/api_key.rs
  src/command/config/mod.rs
  src/command/config/profile.rs
  src/command/schema/fetch.rs
  src/command/schema/mod.rs
  src/lib.rs
  src/telemetry.rs
Labels: changelog - feature, status - needs review

#54 Use tracing instead of log/env_logger
  Cargo.lock
  Cargo.toml
  crates/houston/Cargo.toml
  crates/houston/src/lib.rs
  crates/houston/src/profile/mod.rs
  crates/houston/src/profile/sensitive.rs
  crates/timber/Cargo.toml
  crates/timber/README.md
  crates/timber/src/formatter.rs
  crates/timber/src/lib.rs
  docs/gatsby-config.js
  docs/source/usage/config/log.md
  src/bin/rover.rs
  src/cli.rs
  src/command/config/api_key.rs
  src/command/config/mod.rs
  src/command/config/profile.rs
  src/command/schema/fetch.rs
  src/lib.rs
  src/logger.rs
  src/stringify.rs
  src/telemetry.rs
Labels: product - feature, status - needs review

#67 fix(timber): subscriber s/stdout/stderr
  crates/timber/src/formatter.rs
  tests/config/profile.rs
Labels: changelog - fix, status - needs review
