Repository apollographql/rover, pull requests merged in 2020-11, with the labels that each got.

#72 chore(houston): updates directories to directories-next
  Cargo.lock
  crates/houston/Cargo.toml
  crates/houston/src/home.rs
Labels: operations - maintenance, status - needs review

#73 clean up houston error handling
  crates/houston/src/error.rs
  crates/houston/src/lib.rs
  crates/houston/src/profile/mod.rs
  crates/houston/tests/api-key.rs
  crates/houston/tests/profile.rs
  src/command/config/api_key.rs
  src/command/config/profile.rs
Labels: operations - feature, status - needs review

#69 feat: crash report panic handler
  Cargo.lock
  Cargo.toml
  crates/robot-panic/Cargo.toml
  crates/robot-panic/README.md
  crates/robot-panic/src/lib.rs
  crates/robot-panic/src/report.rs
  src/bin/rover.rs
Labels: product - feature, status - needs review

#68 standardize command return type
  Cargo.lock
  Cargo.toml
  crates/apollo/Cargo.toml
  crates/apollo/src/lib.rs
  src/bin/rover.rs
  src/cli.rs
  src/command/config/api_key.rs
  src/command/config/clear.rs
  src/command/config/mod.rs
  src/command/config/profile.rs
  src/command/mod.rs
  src/command/output.rs
  src/command/partial/mod.rs
  src/command/partial/push.rs
  src/command/schema/fetch.rs
  src/command/schema/mod.rs
  src/command/schema/push.rs
Labels: operations - maintenance, status - needs review

#82 Clean up & make docs more consistent
  src/cli.rs
  src/command/partial/mod.rs
  src/command/partial/push.rs
  src/command/schema/fetch.rs
  src/command/schema/mod.rs
  src/command/schema/push.rs
Labels: status - working in progress

#76 Split up generic/studio clients
  crates/rover-client/src/blocking/client.rs
  crates/rover-client/src/blocking/mod.rs
  crates/rover-client/src/blocking/studio_client.rs
  crates/rover-client/src/error.rs
  crates/rover-client/src/headers.rs
  crates/rover-client/src/query/partial/push.rs
  crates/rover-client/src/query/schema/get.rs
  crates/rover-client/src/query/schema/push.rs
  src/client.rs
  src/command/partial/push.rs
  src/command/schema/fetch.rs
  src/command/schema/push.rs
Labels: product - feature, status - working in progress

#78 feat: npm installer
  installers/npm/.gitignore
  installers/npm/binary.js
  installers/npm/install.js
  installers/npm/package-lock.json
  installers/npm/package.json
  installers/npm/run.js
Labels: operations - feature, status - needs review

#83 Clean up API-related errors
  crates/rover-client/src/blocking/client.rs
  crates/rover-client/src/blocking/studio_client.rs
  crates/rover-client/src/error.rs
  crates/rover-client/src/query/partial/push.rs
  crates/rover-client/src/query/schema/get.rs
  crates/rover-client/src/query/schema/push.rs
  src/command/config/api_key.rs
  src/command/config/clear.rs
  src/command/partial/push.rs
  src/command/schema/fetch.rs
  src/command/schema/push.rs
Labels: product - feature, status - needs review

#79 fix: remove deprecated add-path usage
  .github/workflows/release.yml
Labels: operations - maintenance, status - needs review

#86 feat: less verbose logger
  crates/timber/Cargo.toml
  crates/timber/src/formatter.rs
Labels: operations - feature, status - needs review

#80 curl | sh installer :)
  Cargo.lock
  Cargo.toml
  crates/rover-client/Cargo.toml
  installers/binstall/Cargo.toml
  installers/binstall/install.sh
  installers/binstall/local-install.sh
  installers/binstall/src/error.rs
  installers/binstall/src/install.rs
  installers/binstall/src/lib.rs
  installers/binstall/src/system/env.sh
  installers/binstall/src/system/mod.rs
  installers/binstall/src/system/unix.rs
  installers/binstall/src/system/windows.rs
  src/bin/rover.rs
  src/cli.rs
  src/command/install/mod.rs
  src/command/mod.rs
Labels: operations - feature, status - needs review

#91 fix(docs): always run netlify build
  netlify.toml
Labels: operations - maintenance
