Repository apollographql/rover, pull requests merged in 2020-12, with the labels that each got.

#108 use stdin as sdl input
  src/command/graph/push.rs
  src/command/subgraph/push.rs
  src/lib.rs
  src/utils/loaders.rs
  src/utils/mod.rs
  src/utils/parsers.rs
Labels: product - feature

#95 Make graph_name input consistent across commands
  Cargo.lock
  Cargo.toml
  src/command/graph/fetch.rs
  src/command/graph/push.rs
  src/command/subgraph/delete.rs
  src/command/subgraph/push.rs
  src/utils/parsers.rs
Labels: status - needs review

#119 feat(client): auto-update schema
  Cargo.lock
  crates/rover-client/.gitignore
  crates/rover-client/Cargo.toml
  crates/rover-client/build.rs
  crates/rover-client/schema.graphql
  crates/rover-client/src/query/partial/delete.rs
  crates/rover-client/src/query/partial/push.rs
  crates/rover-client/src/query/schema/get.rs
  crates/rover-client/src/query/schema/push.rs
Labels: operations - feature

#120 chore: fix latest clippy warnings
  crates/rover-client/src/query/partial/push.rs
  src/telemetry.rs
Labels: operations - maintenance, status - needs review

#114 feat(rover): config api-key -> config profile auth
  docs/source/usage/config/authentication.md
  docs/source/usage/config/index.md
  docs/source/usage/config/profiles.md
  src/command/config/clear.rs
  src/command/config/mod.rs
  src/command/config/profile.rs
  src/command/config/profile/auth.rs
  src/command/config/profile/delete.rs
  src/command/config/profile/list.rs
  src/command/config/profile/mod.rs
  src/command/config/profile/show.rs
  tests/config/api_key.rs
Labels: status - needs decision, status - needs review

#104 feat: windows installer
  Cargo.lock
  installers/binstall/Cargo.toml
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/nix/local-install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/binstall/scripts/windows/local-install.ps1
  installers/binstall/src/system/windows.rs
Labels: operations - feature, status - needs review

#125 chore: finish renaming subgraph and graph
  crates/rover-client/src/query/graph/fetch.graphql
  crates/rover-client/src/query/graph/fetch.rs
  crates/rover-client/src/query/graph/mod.rs
  crates/rover-client/src/query/graph/push.graphql
  crates/rover-client/src/query/graph/push.rs
  crates/rover-client/src/query/mod.rs
  crates/rover-client/src/query/partial/mod.rs
  crates/rover-client/src/query/schema/mod.rs
  crates/rover-client/src/query/subgraph/delete.graphql
  crates/rover-client/src/query/subgraph/delete.rs
  crates/rover-client/src/query/subgraph/mod.rs
  crates/rover-client/src/query/subgraph/push.graphql
  crates/rover-client/src/query/subgraph/push.rs
  src/command/graph/fetch.rs
  src/command/graph/push.rs
  src/command/subgraph/delete.rs
  src/command/subgraph/push.rs
Labels: operations - maintenance, status - needs review

#128 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: operations - maintenance

#75 central environment variable store
  Cargo.lock
  Cargo.toml
  crates/houston/Cargo.toml
  crates/houston/src/config.rs
  crates/houston/src/error.rs
  crates/houston/src/home.rs
  crates/houston/src/lib.rs
  crates/houston/src/profile/mod.rs
  crates/houston/src/profile/sensitive.rs
  crates/houston/tests/auth.rs
  crates/houston/tests/profile.rs
  crates/rover-client/src/lib.rs
  crates/sputnik/src/report.rs
  crates/sputnik/src/session.rs
  src/cli.rs
  src/client.rs
  src/command/config/clear.rs
  src/command/config/mod.rs
  src/command/config/profile/auth.rs
  src/command/config/profile/delete.rs
  src/command/config/profile/list.rs
  src/command/config/profile/mod.rs
  src/command/config/profile/show.rs
  src/command/graph/fetch.rs
  src/command/graph/mod.rs
  src/command/graph/push.rs
  src/command/install/mod.rs
  src/command/subgraph/delete.rs
  src/command/subgraph/fetch.rs
  src/command/subgraph/mod.rs
  src/command/subgraph/push.rs
  src/env.rs
  src/lib.rs
  src/telemetry.rs
  tests/config/profile.rs
Labels: operations - feature, status - needs review

#126 feat(rover): rover graph check
  Cargo.lock
  Cargo.toml
  crates/rover-client/Cargo.toml
  crates/rover-client/src/error.rs
  crates/rover-client/src/query/graph/check.graphql
  crates/rover-client/src/query/graph/check.rs
  crates/rover-client/src/query/graph/mod.rs
  src/command/graph/check.rs
  src/command/graph/mod.rs
Labels: product - feature, status - needs review

#145 chore: get graph check up to speed
  src/command/graph/check.rs
Labels: product - feature

#150 feat: update npm package in build step
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
  RELEASE_CHECKLIST.md
  build.rs
  installers/npm/LICENSE
  installers/npm/README.md
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: operations - feature

#151 fix(npm): call rover.exe on windows instead of rover
  installers/npm/binary.js
  installers/npm/package.json
Labels: operations - bug

#153 chore(docs): update documentation for v0.0.1-rc.1
  README.md
  installers/npm/README.md
  installers/npm/package.json
Labels: docs - external, docs - github
