Repository apollographql/rover, pull requests merged in 2020-09, with the labels that each got.

#38 removes flaky profile test
  crates/houston/tests/profile.rs
Labels: changelog - fix, status - needs review

#42 makes Ashley, Avery, and Jake CODEOWNERS
  CODEOWNERS
Labels: operations - maintenance, status - needs review

#41 updates console to 0.12.0
  Cargo.lock
  Cargo.toml
Labels: operations - maintenance, status - needs review

#34 adds CI for cutting releases
  .github/workflows/release.yml
Labels: operations - feature, status - needs review

#39 Integrate Apollo Gatsby Docs
  README.md
  docs/.gitignore
  docs/book.toml
  docs/gatsby-config.js
  docs/package-lock.json
  docs/package.json
  docs/source/contributing/documentation.md
  docs/source/contributing/index.md
  docs/source/contributing/prerequisites.md
  docs/source/contributing/project-structure.md
  docs/source/index.mdx
  docs/source/usage/config/authentication.md
  docs/source/usage/config/environment-variables.md
  docs/source/usage/config/index.md
  docs/source/usage/config/profiles.md
  docs/source/usage/index.md
  docs/src/SUMMARY.md
  docs/src/contributing/documentation.md
  docs/src/contributing/index.md
  docs/src/getting-started/index.md
  docs/static/_redirects
  netlify.toml
Labels: docs - external, status - needs review

#36 adds first version of release checklist
  RELEASE_CHECKLIST.md
Labels: operations - feature, status - needs review

#35 adds first version of CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: docs - github, operations - maintenance, status - needs review

#49 removes old mdbook deploy gh action
  .github/workflows/docs.yml
Labels: operations - maintenance
