Repository apollographql/rover, pull requests merged in 2021-06, with the labels that each got.

#593 chore(deps): bump semver from 0.11.0 to 1.0.2
  Cargo.lock
  Cargo.toml
  crates/sputnik/Cargo.toml
  crates/sputnik/src/error.rs
Labels: maintenance 🛠️

#592 fix: don't panic on empty error array
  crates/rover-client/src/blocking/client.rs
  crates/rover-client/src/blocking/mod.rs
  crates/rover-client/src/blocking/studio_client.rs
  crates/rover-client/src/query/graph/introspect.rs
  crates/rover-client/src/query/subgraph/introspect.rs
  src/command/graph/introspect.rs
  src/command/subgraph/introspect.rs
  src/command/supergraph/compose/do_compose.rs
Labels: fix 🩹

#562 feat: cargo xtask
  .cargo/config
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  ARCHITECTURE.md
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  RELEASE_CHECKLIST.md
  build.rs
  crates/rover-client/src/query/graph/mod.rs
  docs/source/contributing.md
  netlify.toml
  xtask/Cargo.toml
  xtask/README.md
  xtask/src/commands/cargo/mod.rs
  xtask/src/commands/cargo/runner.rs
  xtask/src/commands/cargo/target.rs
  xtask/src/commands/dist/mod.rs
  xtask/src/commands/dist/strip.rs
  xtask/src/commands/lint.rs
  xtask/src/commands/mod.rs
  xtask/src/commands/prep/docs.rs
  xtask/src/commands/prep/installers.rs
  xtask/src/commands/prep/mod.rs
  xtask/src/commands/prep/npm.rs
  xtask/src/commands/test.rs
  xtask/src/main.rs
  xtask/src/utils.rs
Labels: maintenance 🛠️

#621 chore: address clippy 0.1.53 warnings
  crates/rover-client/build.rs
Labels: maintenance 🛠️

#620 feat(client): auto-decode gzipped responses
  Cargo.lock
  crates/rover-client/Cargo.toml
  crates/rover-client/src/blocking/client.rs
  crates/rover-client/src/blocking/studio_client.rs
  crates/rover-client/tests/client.rs
  src/command/graph/introspect.rs
  src/command/subgraph/introspect.rs
  src/command/supergraph/compose/do_compose.rs
  src/utils/client.rs
Labels: feature 🎉

#623 chore: updates deps
  Cargo.lock
  Cargo.toml
  src/command/output.rs
Labels: dependencies, maintenance 🛠️

#624 fix: don't fail command on failed version check && use rustls
  crates/rover-client/src/blocking/client.rs
  src/cli.rs
Labels: maintenance 🛠️

#627 Revert "release: v0.1.7 (#625)"
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  docs/source/contributing.md
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: fix 🩹

#628 fix(docs): update netlify docs
  docs/source/contributing.md
Labels: docs 📝

#634 Bump online from 0.2.2 to 3.0.0
  Cargo.lock
  crates/rover-client/Cargo.toml
  crates/rover-client/build.rs
Labels: dependencies
