Repository apollographql/rover, pull requests merged in 2021-03, with the labels that each got.

#314 feat: adds `rover docs open` and `rover docs list`
  Cargo.lock
  Cargo.toml
  src/cli.rs
  src/command/config/auth.rs
  src/command/docs/list.rs
  src/command/docs/mod.rs
  src/command/docs/open.rs
  src/command/docs/shortlinks.rs
  src/command/mod.rs
  src/command/output.rs
  src/error/metadata/suggestion.rs
Labels: feature 🎉

#315 feat: prettier table
  installers/npm/package-lock.json
  src/command/graph/check.rs
  src/command/output.rs
  src/command/subgraph/check.rs
  src/utils/mod.rs
  src/utils/table.rs
Labels: feature 🎉

#318 feat(binstall): don't require terminal reload
  installers/binstall/src/system/unix.rs
  src/command/install/mod.rs
Labels: feature 🎉

#319 feat: check for available updates
  Cargo.lock
  Cargo.toml
  crates/rover-client/Cargo.toml
  crates/rover-client/src/error.rs
  crates/rover-client/src/lib.rs
  crates/rover-client/src/releases.rs
  src/cli.rs
  src/command/mod.rs
  src/command/update/check.rs
  src/command/update/mod.rs
  src/error/metadata/mod.rs
  src/utils/mod.rs
  src/utils/version.rs
Labels: feature 🎉

#316 feat: error message for invalid variants
  Cargo.lock
  Cargo.toml
  crates/rover-client/src/error.rs
  crates/rover-client/src/query/graph/fetch.graphql
  crates/rover-client/src/query/graph/fetch.rs
  src/bin/rover.rs
  src/command/output.rs
  src/error/metadata/mod.rs
  src/error/metadata/suggestion.rs
Labels: feature 🎉

#321 chore: assert stable installer script URLs
  tests/installers.rs
Labels: maintenance 🛠️

#323 feat: squash config show into config whoami
  crates/houston/src/profile/mod.rs
  crates/houston/src/profile/sensitive.rs
  src/command/config/mod.rs
  src/command/config/show.rs
  src/command/config/whoami.rs
  src/error/metadata/mod.rs
  src/error/metadata/suggestion.rs
  src/utils/telemetry.rs
Labels: feature 🎉

#324 Add version defaults to install scripts
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
Labels: feature 🎉

#326 feat: enforce all Paths to be valid Unicode
  Cargo.lock
  Cargo.toml
  build.rs
  crates/houston/Cargo.toml
  crates/houston/src/config.rs
  crates/houston/src/error.rs
  crates/houston/src/profile/mod.rs
  crates/houston/src/profile/sensitive.rs
  crates/houston/tests/auth.rs
  crates/houston/tests/profile.rs
  crates/robot-panic/Cargo.toml
  crates/robot-panic/src/lib.rs
  crates/robot-panic/src/report.rs
  crates/rover-client/Cargo.toml
  crates/rover-client/build.rs
  crates/sputnik/Cargo.toml
  crates/sputnik/src/report.rs
  installers/binstall/Cargo.toml
  installers/binstall/src/error.rs
  installers/binstall/src/install.rs
  installers/binstall/src/lib.rs
  installers/binstall/src/system/unix.rs
  installers/binstall/src/system/windows.rs
  installers/npm/package-lock.json
  src/cli.rs
  src/command/config/auth.rs
  src/command/install/mod.rs
  src/error/metadata/mod.rs
  src/utils/loaders.rs
  src/utils/parsers.rs
  src/utils/telemetry.rs
  src/utils/version.rs
  tests/config/profile.rs
  tests/installers.rs
Labels: feature 🎉

#332 chore: auto bump versions in our windows/nix install scripts
  Cargo.toml
  build.rs
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
Labels: maintenance 🛠️

#335 fix: output composition errors to stderr
  installers/binstall/src/system/windows.rs
  src/command/subgraph/check.rs
Labels: fix 🩹

#341 docs: adds APOLLO_HOME to env var list
  docs/source/configuring.md
Labels: docs 📝

#333 chore: updates README to 0.0.3 help text
  README.md
  RELEASE_CHECKLIST.md
  build.rs
  installers/npm/.gitignore
  installers/npm/LICENSE
  installers/npm/README.md
  installers/npm/package.json
Labels: maintenance 🛠️

#325 Docs for installing older versions
  README.md
  docs/source/getting-started.md
Labels: docs 📝

#346 chore: updates Cargo.toml metadata
  Cargo.toml
Labels: maintenance 🛠️

#347 push -> publish
  README.md
  crates/rover-client/src/query/graph/check.rs
  crates/rover-client/src/query/graph/mod.rs
  crates/rover-client/src/query/graph/publish.graphql
  crates/rover-client/src/query/graph/publish.rs
  crates/rover-client/src/query/subgraph/check.rs
  crates/rover-client/src/query/subgraph/mod.rs
  crates/rover-client/src/query/subgraph/publish.graphql
  crates/rover-client/src/query/subgraph/publish.rs
  docs/source/configuring.md
  docs/source/graphs.md
  docs/source/index.mdx
  docs/source/subgraphs.md
  src/cli.rs
  src/command/graph/check.rs
  src/command/graph/mod.rs
  src/command/graph/publish.rs
  src/command/subgraph/check.rs
  src/command/subgraph/mod.rs
  src/command/subgraph/publish.rs
  src/utils/git.rs
Labels: BREAKING :exclamation:, docs 📝, maintenance 🛠️

#339 fix: s/committer/author
  docs/source/configuring.md
  src/utils/env.rs
  src/utils/git.rs
Labels: fix 🩹

#342 chore: don't message if Rover is already up to date
  src/utils/version.rs
Labels: maintenance 🛠️

#340 feat(spike): rover core build
  Cargo.lock
  Cargo.toml
  installers/npm/package-lock.json
  src/cli.rs
  src/command/core/build.rs
  src/command/core/config.rs
  src/command/core/mod.rs
  src/command/graph/mod.rs
  src/command/mod.rs
  src/command/output.rs
  src/command/subgraph/check.rs
Labels: feature 🎉

#283 feat: introspection SDL encoder
  Cargo.lock
  Cargo.toml
  crates/rover-client/Cargo.toml
  crates/rover-client/src/error.rs
  crates/rover-client/src/introspection/mod.rs
  crates/rover-client/src/introspection/schema.rs
  crates/rover-client/src/lib.rs
  crates/rover-client/src/query/graph/introspect.rs
  crates/rover-client/src/query/graph/introspect_query.graphql
  crates/rover-client/src/query/graph/introspect_schema.graphql
  crates/rover-client/src/query/graph/mod.rs
  crates/rover-client/tests/fixtures/interfaces.json
  crates/rover-client/tests/fixtures/simple.json
  crates/rover-client/tests/fixtures/swapi.json
  crates/rover-client/tests/schema.rs
  crates/sdl-encoder/Cargo.toml
  crates/sdl-encoder/src/directive_def.rs
  crates/sdl-encoder/src/enum_def.rs
  crates/sdl-encoder/src/enum_value.rs
  crates/sdl-encoder/src/field.rs
  crates/sdl-encoder/src/field_value.rs
  crates/sdl-encoder/src/input_field.rs
  crates/sdl-encoder/src/input_object_def.rs
  crates/sdl-encoder/src/input_value.rs
  crates/sdl-encoder/src/interface_def.rs
  crates/sdl-encoder/src/lib.rs
  crates/sdl-encoder/src/object_def.rs
  crates/sdl-encoder/src/scalar_def.rs
  crates/sdl-encoder/src/schema.rs
  crates/sdl-encoder/src/schema_def.rs
  crates/sdl-encoder/src/union_def.rs
  src/command/graph/introspect.rs
  src/command/graph/mod.rs
  src/command/output.rs
  src/error/metadata/mod.rs
  src/utils/parsers.rs
Labels: feature 🎉

#364 chore: address new clippy 0.1.51 warnings
  crates/houston/src/error.rs
  crates/houston/src/profile/mod.rs
  crates/rover-client/src/blocking/client.rs
  crates/rover-client/src/error.rs
  crates/rover-client/src/lib.rs
  crates/sputnik/src/error.rs
  installers/binstall/src/error.rs
  src/command/core/build.rs
  src/command/graph/fetch.rs
  src/command/output.rs
  src/command/subgraph/fetch.rs
  src/error/metadata/mod.rs
  src/utils/git.rs
Labels: maintenance 🛠️

#363 chore: adds MacOS signing and notarization to CI process
  .github/workflows/release.yml
Labels: maintenance 🛠️

#365 chore: adds rust caching to clippy
  .github/workflows/lint.yml
Labels: maintenance 🛠️

#381 infra: test, build and release on ubuntu-16.04
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test-nightly.yml
  .github/workflows/test.yml
Labels: fix 🩹

#389 Release docs
  docs/gatsby-config.js
  docs/source/ci-cd.md
  docs/source/configuring.md
  docs/source/essentials.md
  docs/source/getting-started.md
  docs/source/graphs.md
  docs/source/index.mdx
  docs/source/subgraphs.md
  docs/source/supergraphs.md
Labels: docs 📝

#400 chore(binstall): remove binary before overwriting it
  installers/binstall/src/install.rs
Labels: fix 🩹
