Repository apollographql/rover, pull requests merged in 2021-08, with the labels that each got.

#697 fix: updates types to match new schema
  .cargo/config
  .github/workflows/release.yml
  Cargo.lock
  README.md
  crates/robot-panic/src/lib.rs
  crates/rover-client/build.rs
  crates/rover-client/package-lock.json
  crates/rover-client/src/blocking/client.rs
  crates/rover-client/src/operations/subgraph/check/runner.rs
  crates/rover-client/src/operations/subgraph/publish/runner.rs
  crates/rover-client/tests/client.rs
  installers/npm/package-lock.json
  src/command/output.rs
  src/command/supergraph/compose/do_compose.rs
  src/utils/loaders.rs
  xtask/Cargo.toml
  xtask/README.md
  xtask/src/commands/dist.rs
  xtask/src/commands/lint.rs
  xtask/src/commands/mod.rs
  xtask/src/commands/prep/docs.rs
  xtask/src/commands/prep/installers.rs
  xtask/src/commands/test.rs
  xtask/src/commands/version.rs
  xtask/src/target.rs
  xtask/src/tools/cargo.rs
  xtask/src/tools/git.rs
  xtask/src/tools/make.rs
  xtask/src/tools/npm.rs
  xtask/src/tools/runner.rs
  xtask/src/tools/strip.rs
  xtask/src/utils.rs
Labels: fix 🩹

#706 docs: Fix link to supergraph schemas
  docs/source/supergraphs.md
Labels: docs 📝

#707 chore(deps): updates graphql-client to v0.10.0
  Cargo.lock
  crates/rover-client/Cargo.toml
  crates/rover-client/src/operations/graph/check/types.rs
  crates/rover-client/src/operations/graph/introspect/schema.rs
  crates/rover-client/src/operations/graph/publish/types.rs
  crates/rover-client/src/operations/subgraph/check/types.rs
  crates/rover-client/src/operations/subgraph/publish/types.rs
Labels: maintenance 🛠️, dependencies, size/small, 2021-08

#726 fix: adds error message for empty SDL
  src/utils/loaders.rs
  subgraphs/reviews.graphql
Labels: fix 🩹

#730 fix(xtask): use correct default target if not x86_64
  xtask/src/target.rs
Labels: fix 🩹, size/small, 2021-08

#732 fix(robot-panic): use our bug report template for panics
  crates/robot-panic/src/lib.rs
  crates/robot-panic/src/report.rs
  src/bin/rover.rs
Labels: feature 🎉, 2021-08

#731 fix: don't panic on git remotes w/no apparent owner
  crates/rover-client/src/shared/git_context.rs
Labels: fix 🩹, 2021-08

#743 chore: updates deps
  Cargo.lock
Labels: dependencies, size/small, 2021-08

#738 fix(rover-client): properly send validation period config
  crates/rover-client/src/operations/graph/check/types.rs
  crates/rover-client/src/operations/subgraph/check/types.rs
  crates/rover-client/src/shared/check_response.rs
  subgraphs/reviews.graphql
Labels: fix 🩹, 2021-08

#742 sdl-encoder: fix description encodings
  crates/rover-client/src/operations/graph/introspect/schema.rs
  crates/sdl-encoder/src/description.rs
  crates/sdl-encoder/src/directive_def.rs
  crates/sdl-encoder/src/enum_def.rs
  crates/sdl-encoder/src/enum_value.rs
  crates/sdl-encoder/src/field.rs
  crates/sdl-encoder/src/input_field.rs
  crates/sdl-encoder/src/input_object_def.rs
  crates/sdl-encoder/src/input_value.rs
  crates/sdl-encoder/src/interface_def.rs
  crates/sdl-encoder/src/lib.rs
  crates/sdl-encoder/src/object_def.rs
  crates/sdl-encoder/src/scalar_def.rs
  crates/sdl-encoder/src/schema_def.rs
  crates/sdl-encoder/src/union_def.rs
Labels: fix 🩹, size/small, 2021-08

#727 feat: adds HTTP retries for responses w/statuses 500-599
  Cargo.lock
  crates/rover-client/Cargo.toml
  crates/rover-client/src/blocking/client.rs
  crates/rover-client/src/blocking/studio_client.rs
Labels: feature 🎉

#747 chore: add cargo update to xtask prep
  Cargo.lock
  crates/rover-client/package-lock.json
  installers/npm/package-lock.json
  xtask/src/commands/prep/mod.rs
  xtask/src/tools/cargo.rs
Labels: maintenance 🛠️

#751 fix(rover-client): send request body as string
  crates/rover-client/src/blocking/client.rs
  crates/rover-client/src/blocking/studio_client.rs
Labels: fix 🩹

#752 chore: updates json_version from 1.beta to 1
  src/command/output.rs
Labels: maintenance 🛠️

#750 docs: document `--output json`
  docs/package-lock.json
  docs/source/configuring.md
Labels: docs 📝

#753 chore(rover-client): DRY out studio-client
  crates/rover-client/src/blocking/client.rs
  crates/rover-client/src/blocking/mod.rs
  crates/rover-client/src/blocking/studio_client.rs
  crates/rover-client/src/operations/graph/introspect/runner.rs
  crates/rover-client/src/operations/subgraph/introspect/runner.rs
  src/command/graph/introspect.rs
  src/command/subgraph/introspect.rs
Labels: maintenance 🛠️, size/small, 2021-08

#757 release: v0.2.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  crates/rover-client/package-lock.json
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 2021-08

#777 chore: updates deps
  Cargo.lock
  Cargo.toml
Labels: maintenance 🛠️, dependencies
