Repository apollographql/rover, pull requests merged in 2021-11, with the labels that each got.

#919 fix(sdl-encoder): indent multiline field comments
  crates/rover-client/src/operations/graph/introspect/schema.rs
  crates/sdl-encoder/src/description.rs
  crates/sdl-encoder/src/enum_value.rs
  crates/sdl-encoder/src/interface_def.rs
  crates/sdl-encoder/src/object_def.rs
Labels: 2021-11

#929 chore: bumps harmonizer to 0.33.7
  Cargo.lock
  Cargo.toml
Labels: maintenance 🛠️

#930 sdl-encoder: encode string values with single quotes (")
  crates/rover-client/src/operations/graph/introspect/schema.rs
  crates/sdl-encoder/src/description.rs
  crates/sdl-encoder/src/directive_def.rs
  crates/sdl-encoder/src/enum_def.rs
  crates/sdl-encoder/src/enum_value.rs
  crates/sdl-encoder/src/field.rs
  crates/sdl-encoder/src/input_object_def.rs
  crates/sdl-encoder/src/input_value.rs
  crates/sdl-encoder/src/interface_def.rs
  crates/sdl-encoder/src/lib.rs
  crates/sdl-encoder/src/object_def.rs
  crates/sdl-encoder/src/scalar_def.rs
  crates/sdl-encoder/src/schema.rs
  crates/sdl-encoder/src/union_def.rs
Labels: size/small, 2021-11

#928 feat: adds support for SOCKS proxies and documents existing proxy support
  Cargo.lock
  crates/rover-client/Cargo.toml
  crates/sputnik/Cargo.toml
  docs/gatsby-config.js
  docs/source/migration.md
  docs/source/proxy.md
  installers/binstall/Cargo.toml
Labels: docs 📝, feature 🎉

#931 release: v0.4.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  crates/rover-client/package-lock.json
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/nix/install_rover_fed2.sh
  installers/binstall/scripts/windows/install.ps1
  installers/binstall/scripts/windows/install_rover_fed2.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
  plugins/rover-fed2/Cargo.lock
  plugins/rover-fed2/Cargo.toml
Labels: 2021-11
