Repository apollographql/rover, pull requests merged in 2021-05, with the labels that each got.

#473 chore: removes automated steps from release checklist
  RELEASE_CHECKLIST.md
Labels: maintenance 🛠️

#493 chore: removes unnecessary URL parser
  CHANGELOG.md
  src/command/graph/introspect.rs
  src/command/subgraph/introspect.rs
  src/utils/parsers.rs
Labels: maintenance 🛠️

#460 chore(ci): checks for broken links
  .github/workflows/lint.yml
  CHANGELOG.md
  README.md
  crates/robot-panic/README.md
  mlc_config.json
Labels: maintenance 🛠️

#487 feat: removes -V from subcommands + strict utf-8
  CHANGELOG.md
  src/cli.rs
Labels: BREAKING :exclamation:, feature 🎉

#494 feat(binstall): error on missing glibc
  CHANGELOG.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/nix/local-install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/binstall/scripts/windows/local-install.ps1
Labels: feature 🎉

#484 feat: makes subgraph routing-url optional
  CHANGELOG.md
  crates/rover-client/src/query/subgraph/publish.graphql
  docs/source/subgraphs.md
  src/command/subgraph/publish.rs
Labels: feature 🎉

#503 feat: adds `rover docs open migration`
  CHANGELOG.md
  src/command/docs/shortlinks.rs
Labels: feature 🎉

#506 fix: ignore routing url argument in telemetry
  src/command/subgraph/publish.rs
Labels: fix 🩹

#515 chore: address clippy 1.52 warnings
  crates/rover-client/src/query/subgraph/delete.rs
  crates/rover-client/src/query/subgraph/publish.rs
Labels: maintenance 🛠️

#485 feat: `rover supergraph fetch`
  crates/rover-client/src/error.rs
  crates/rover-client/src/query/mod.rs
  crates/rover-client/src/query/supergraph/fetch.graphql
  crates/rover-client/src/query/supergraph/fetch.rs
  crates/rover-client/src/query/supergraph/mod.rs
  src/cli.rs
  src/command/output.rs
  src/command/supergraph/fetch.rs
  src/command/supergraph/mod.rs
  src/error/metadata/mod.rs
  src/error/metadata/suggestion.rs
  src/utils/env.rs
Labels: feature 🎉

#516 fix(whoami): $APOLLO_KEY works with no default profile
  CHANGELOG.md
  crates/houston/src/profile/mod.rs
  src/cli.rs
  src/command/config/mod.rs
  src/command/config/whoami.rs
  src/utils/client.rs
Labels: fix 🩹

#518 feat: RoverClientError::CouldNotConnect
  CHANGELOG.md
  crates/rover-client/src/blocking/client.rs
  crates/rover-client/src/error.rs
  src/error/metadata/mod.rs
  src/error/metadata/suggestion.rs
Labels: feature 🎉

#457 Add error codes
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  build.rs
  docs/gatsby-config.js
  docs/source/errors.md
  installers/npm/package-lock.json
  src/cli.rs
  src/command/explain.rs
  src/command/mod.rs
  src/command/output.rs
  src/error/metadata/code.rs
  src/error/metadata/codes/E001.md
  src/error/metadata/codes/E002.md
  src/error/metadata/codes/E003.md
  src/error/metadata/codes/E004.md
  src/error/metadata/codes/E005.md
  src/error/metadata/codes/E006.md
  src/error/metadata/codes/E007.md
  src/error/metadata/codes/E008.md
  src/error/metadata/codes/E009.md
  src/error/metadata/codes/E010.md
  src/error/metadata/codes/E011.md
  src/error/metadata/codes/E012.md
  src/error/metadata/codes/E013.md
  src/error/metadata/codes/E014.md
  src/error/metadata/codes/E015.md
  src/error/metadata/codes/E016.md
  src/error/metadata/codes/E017.md
  src/error/metadata/codes/E018.md
  src/error/metadata/codes/E019.md
  src/error/metadata/codes/E020.md
  src/error/metadata/codes/E021.md
  src/error/metadata/codes/E022.md
  src/error/metadata/codes/E023.md
  src/error/metadata/codes/E024.md
  src/error/metadata/codes/E025.md
  src/error/metadata/codes/E026.md
  src/error/metadata/codes/E027.md
  src/error/metadata/codes/E028.md
  src/error/metadata/mod.rs
  src/error/mod.rs
Labels: docs 📝, feature 🎉

#491 (docs) Using Rover with Bitbucket Pipelines
  docs/source/ci-cd.md
Labels: docs 📝

#532 fixup: log levels/wording
  installers/binstall/src/install.rs
  src/command/graph/publish.rs
  src/command/subgraph/publish.rs
  src/utils/env.rs
  src/utils/telemetry.rs
  src/utils/version.rs
Labels: fix 🩹

#538 feat: Build Rover without `supergraph compose` for Alpine
  .github/workflows/release.yml
  .github/workflows/test.yml
  Cargo.lock
  Cargo.toml
  README.md
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/npm/binary.js
  installers/npm/package-lock.json
  installers/npm/package.json
  src/command/install/mod.rs
  src/command/supergraph/compose/do_compose.rs
  src/command/supergraph/compose/mod.rs
  src/command/supergraph/compose/no_compose.rs
  src/command/supergraph/config.rs
  src/error/metadata/suggestion.rs
Labels: feature 🎉

#549 fix: removes unwrap from is_federated query
  crates/rover-client/src/error.rs
  crates/rover-client/src/query/config/is_federated.rs
  crates/rover-client/src/query/graph/fetch.rs
  crates/rover-client/src/query/graph/publish.rs
  crates/rover-client/src/query/subgraph/check.rs
  crates/rover-client/src/query/subgraph/delete.rs
  crates/rover-client/src/query/subgraph/fetch.rs
  crates/rover-client/src/query/subgraph/introspect.rs
  crates/rover-client/src/query/subgraph/list.rs
  crates/rover-client/src/query/subgraph/publish.rs
  crates/rover-client/src/query/supergraph/fetch.rs
  src/command/subgraph/check.rs
  src/command/subgraph/publish.rs
  src/error/metadata/mod.rs
  src/error/metadata/suggestion.rs
Labels: fix 🩹

#547 chore(ci): tweak musl test runners
  .github/workflows/lint.yml
  .github/workflows/test-nightly.yml
  .github/workflows/test.yml
  src/command/supergraph/config.rs
Labels: github_actions, maintenance 🛠️

#558 feat: removes dependency on openssl
  Cargo.lock
  Cargo.toml
  crates/rover-client/Cargo.toml
Labels: fix 🩹

#571 fix: null implementing services
  crates/rover-client/src/query/config/is_federated.rs
Labels: fix 🩹

#580 fix: vendor correct version of OpenSSL
  .github/workflows/release.yml
Labels: fix 🩹

#574 fix: don't squash request errors
  crates/rover-client/src/blocking/client.rs
  crates/rover-client/src/query/subgraph/introspect.rs
  src/error/mod.rs
Labels: fix 🩹
