Repository apollographql/rover, pull requests merged in 2021-01, with the labels that each got.

#158 chore: update dependencies and clean up
  Cargo.lock
  Cargo.toml
  README.md
  RELEASE_CHECKLIST.md
  crates/robot-panic/Cargo.toml
  crates/sputnik/Cargo.toml
  installers/binstall/Cargo.toml
  installers/npm/README.md
  src/command/subgraph/mod.rs
Labels: operations - maintenance

#156 chore: only run CI once per push
  .github/workflows/test.yml
Labels: operations - maintenance

#110 feat(rover): rover subgraph check
  crates/rover-client/src/error.rs
  crates/rover-client/src/query/subgraph/check.graphql
  crates/rover-client/src/query/subgraph/check.rs
  crates/rover-client/src/query/subgraph/mod.rs
  src/command/subgraph/check.rs
  src/command/subgraph/mod.rs
Labels: status - needs review

#161 chore(npm): patches security vulnerability
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: operations - maintenance, status - needs review

#163 chore(npm): s/rover/@apollo/rover
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: operations - maintenance, status - needs review

#160 Rover Docs Rough Pass
  CONTRIBUTING.md
  docs/gatsby-config.js
  docs/package-lock.json
  docs/package.json
  docs/source/configuring.md
  docs/source/contributing.md
  docs/source/contributing/documentation.md
  docs/source/contributing/index.md
  docs/source/contributing/prerequisites.md
  docs/source/contributing/project-structure.md
  docs/source/essentials.md
  docs/source/getting-started.md
  docs/source/graphs.md
  docs/source/index.md
  docs/source/index.mdx
  docs/source/privacy.mdx
  docs/source/privacy/index.md
  docs/source/subgraphs.md
  docs/source/troubleshooting.md
  docs/source/usage/config/authentication.md
  docs/source/usage/config/environment-variables.md
  docs/source/usage/config/index.md
  docs/source/usage/config/log.md
  docs/source/usage/config/profiles.md
  docs/source/usage/index.md
  src/cli.rs
  src/command/config/clear.rs
  src/command/config/profile/auth.rs
  src/command/config/profile/delete.rs
  src/command/config/profile/list.rs
  src/command/config/profile/mod.rs
  src/command/config/profile/show.rs
Labels: docs - external, status - working in progress

#168 fix(rover-client): use prod schema, not staging schema
  crates/rover-client/build.rs
Labels: changelog - fix

#130 Add `subgraph push` option to specify endpoint
  docs/source/subgraphs.md
  src/command/subgraph/push.rs
Labels: product - feature, status - needs review

#172 fix(rover-client): updates composition error types
  crates/rover-client/src/query/subgraph/check.rs
  installers/npm/LICENSE
Labels: changelog - fix

#176 fix(npm): use correct repo url
  installers/npm/binary.js
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: changelog - fix

#184 chore: updates dependencies
  Cargo.lock
  Cargo.toml
  crates/rover-client/Cargo.toml
  crates/sputnik/Cargo.toml
Labels: operations - maintenance, status - needs review

#201 refactor: rename --service-name to --name everywhere
  README.md
  crates/rover-client/src/error.rs
  crates/rover-client/src/query/subgraph/fetch.rs
  docs/source/subgraphs.md
  installers/npm/README.md
  src/command/subgraph/check.rs
  src/command/subgraph/delete.rs
  src/command/subgraph/fetch.rs
  src/command/subgraph/mod.rs
  src/command/subgraph/push.rs
Labels: product - feature, status - needs review

#203 feat(rover): collapse profile commands into config
  crates/sputnik/README.md
  docs/source/configuring.md
  docs/source/getting-started.md
  src/cli.rs
  src/command/config/auth.rs
  src/command/config/delete.rs
  src/command/config/list.rs
  src/command/config/mod.rs
  src/command/config/profile/mod.rs
  src/command/config/show.rs
  src/telemetry.rs
  tests/config/api_key.rs
  tests/config/profile.rs
Labels: product - feature

#198 fix: removing ~/.rover doesn't break future installs
  installers/binstall/src/install.rs
  installers/binstall/src/system/unix.rs
Labels: changelog - fix, status - needs review

#186 Application level error consumption and handling
  Cargo.lock
  Cargo.toml
  src/bin/rover.rs
  src/cli.rs
  src/client.rs
  src/command/config/auth.rs
  src/command/config/clear.rs
  src/command/config/delete.rs
  src/command/config/list.rs
  src/command/config/mod.rs
  src/command/config/show.rs
  src/command/graph/check.rs
  src/command/graph/fetch.rs
  src/command/graph/mod.rs
  src/command/graph/push.rs
  src/command/install/mod.rs
  src/command/subgraph/check.rs
  src/command/subgraph/delete.rs
  src/command/subgraph/fetch.rs
  src/command/subgraph/mod.rs
  src/command/subgraph/push.rs
  src/error/metadata/code.rs
  src/error/metadata/mod.rs
  src/error/metadata/suggestion.rs
  src/error/mod.rs
  src/lib.rs
  src/utils/loaders.rs
  src/utils/parsers.rs
Labels: operations - feature

#206 fix: s/APOLLO_REGISTRY_URI/APOLLO_REGISTRY_URL
  src/cli.rs
  src/env.rs
Labels: changelog - BREAKING, product - feature, status - needs review

#204 Houston, we have some suggestions
  Cargo.toml
  crates/houston/src/config.rs
  crates/houston/src/error.rs
  src/error/metadata/code.rs
  src/error/metadata/mod.rs
  src/error/metadata/suggestion.rs
  tests/config/profile.rs
Labels: product - feature, status - needs review

#185 Add subgraph list command
  Cargo.lock
  Cargo.toml
  crates/rover-client/Cargo.toml
  crates/rover-client/src/query/subgraph/list.graphql
  crates/rover-client/src/query/subgraph/list.rs
  crates/rover-client/src/query/subgraph/mod.rs
  docs/source/subgraphs.md
  src/command/output.rs
  src/command/subgraph/list.rs
  src/command/subgraph/mod.rs
Labels: product - feature, status - needs review

#207 feat: improves introductory logs on graph/subgraph commands
  src/command/graph/check.rs
  src/command/graph/fetch.rs
  src/command/graph/push.rs
  src/command/subgraph/check.rs
  src/command/subgraph/delete.rs
  src/command/subgraph/fetch.rs
  src/command/subgraph/list.rs
  src/command/subgraph/push.rs
  src/env.rs
  src/utils/parsers.rs
Labels: product - feature, status - needs review

#211 fix: removes unnecessary context
  src/command/config/auth.rs
  src/command/config/clear.rs
  src/command/config/delete.rs
  src/command/config/list.rs
  src/command/graph/check.rs
  src/command/graph/push.rs
  src/command/subgraph/check.rs
  src/command/subgraph/fetch.rs
  src/command/subgraph/push.rs
Labels: product - feature, status - needs review

#209 feat(rover-client): improves error handling
  crates/rover-client/src/blocking/client.rs
  crates/rover-client/src/error.rs
  crates/rover-client/src/query/graph/check.rs
  crates/rover-client/src/query/graph/fetch.rs
  crates/rover-client/src/query/graph/push.rs
  crates/rover-client/src/query/subgraph/check.rs
  crates/rover-client/src/query/subgraph/delete.graphql
  crates/rover-client/src/query/subgraph/delete.rs
  crates/rover-client/src/query/subgraph/fetch.rs
  crates/rover-client/src/query/subgraph/list.rs
  crates/rover-client/src/query/subgraph/push.graphql
  crates/rover-client/src/query/subgraph/push.rs
  src/command/subgraph/delete.rs
  src/command/subgraph/push.rs
  src/error/metadata/mod.rs
  src/error/metadata/suggestion.rs
Labels: product - feature, status - needs review
