Repository apollographql/rover, pull requests merged in 2021-02, with the labels that each got.

#205 Add git info to check/push
  Cargo.lock
  Cargo.toml
  crates/rover-client/src/query/graph/check.graphql
  crates/rover-client/src/query/graph/push.graphql
  crates/rover-client/src/query/subgraph/check.graphql
  crates/rover-client/src/query/subgraph/push.graphql
  src/cli.rs
  src/command/graph/check.rs
  src/command/graph/mod.rs
  src/command/graph/push.rs
  src/command/subgraph/check.rs
  src/command/subgraph/mod.rs
  src/command/subgraph/push.rs
  src/env.rs
  src/git.rs
  src/lib.rs
Labels: product - feature, status - needs review

#213 feat: polish command docstrings
  README.md
  installers/npm/README.md
  src/cli.rs
  src/command/graph/mod.rs
  src/command/subgraph/mod.rs
Labels: product - feature, status - needs review

#224 fix(rover-client): reports correct version to graph API
  crates/rover-client/src/blocking/studio_client.rs
  crates/rover-client/src/headers.rs
  src/client.rs
Labels: changelog - fix, status - needs review

#228 fix: error formatting
  crates/rover-client/src/error.rs
  src/bin/rover.rs
Labels: changelog - fix, status - needs review

#218 Add reqwest logs
  crates/rover-client/src/blocking/client.rs
  crates/rover-client/src/blocking/studio_client.rs
Labels: changelog - feature, product - feature, status - needs review

#231 fix: constructs GitContext properly
  src/cli.rs
  src/git.rs
Labels: changelog - fix, status - needs review

#233 chore: GitContext long hash & idiomatic Options
  .github/workflows/test.yml
  Cargo.lock
  Cargo.toml
  src/cli.rs
  src/git.rs
Labels: changelog - fix, status - needs review

#235 Add `rover info` command to print basic info
  Cargo.lock
  Cargo.toml
  src/cli.rs
  src/command/info.rs
  src/command/mod.rs
  tests/info.rs
Labels: product - feature

#234 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: operations - feature, status - working in progress

#229 chore(rover): moves utils into utils dir
  docs/source/contributing.md
  src/cli.rs
  src/command/graph/check.rs
  src/command/graph/fetch.rs
  src/command/graph/mod.rs
  src/command/graph/push.rs
  src/command/subgraph/check.rs
  src/command/subgraph/delete.rs
  src/command/subgraph/fetch.rs
  src/command/subgraph/list.rs
  src/command/subgraph/mod.rs
  src/command/subgraph/push.rs
  src/error/metadata/mod.rs
  src/error/metadata/suggestion.rs
  src/lib.rs
  src/utils/client.rs
  src/utils/env.rs
  src/utils/git.rs
  src/utils/mod.rs
  src/utils/stringify.rs
  src/utils/telemetry.rs
  tests/config/profile.rs
Labels: status - changes requested

#225 Add configurability to checks commands
  crates/rover-client/src/query/graph/check.graphql
  crates/rover-client/src/query/graph/check.rs
  crates/rover-client/src/query/subgraph/check.graphql
  crates/rover-client/src/query/subgraph/check.rs
  src/command/graph/check.rs
  src/command/subgraph/check.rs
  src/utils/parsers.rs
Labels: changelog - feature, product - feature, status - needs review

#267 chore: update for clippy warnings
  crates/houston/src/profile/mod.rs
  crates/houston/src/profile/sensitive.rs
  installers/npm/package-lock.json
  src/command/config/auth.rs
  tests/config/profile.rs
Labels: changelog - maintenance

#269 Fix typo in `README.md`
  README.md
Labels: operations - bug

#270 docs: Suggested edits to Getting Started for npx usage
  docs/source/getting-started.md
Labels: docs - external, docs - github

#281 feat: adds prompt to config auth input
  src/command/config/auth.rs
Labels: status - needs review

#275 fix: handle malformed API key errors
  crates/rover-client/src/blocking/client.rs
  crates/rover-client/src/error.rs
  src/error/metadata/mod.rs
  src/error/metadata/suggestion.rs
Labels: changelog - fix, status - needs review

#282 fix: Make sure Rover works in non-git repos
  src/utils/git.rs
Labels: changelog - fix, product - feature, status - needs review

#297 feat: adds support for big sur in curl installer
  installers/binstall/scripts/nix/install.sh
Labels: feature 🎉

#263 feat(timber): prettier logs
  Cargo.lock
  crates/timber/Cargo.toml
  crates/timber/src/formatter.rs
  crates/timber/src/lib.rs
  installers/binstall/src/install.rs
  out.out
  src/cli.rs
  src/command/config/auth.rs
  src/command/config/clear.rs
  src/command/config/delete.rs
  src/command/config/list.rs
  src/command/config/show.rs
  src/command/config/whoami.rs
  src/command/graph/check.rs
  src/command/graph/fetch.rs
  src/command/graph/push.rs
  src/command/info.rs
  src/command/install/mod.rs
  src/command/output.rs
  src/command/subgraph/check.rs
  src/command/subgraph/delete.rs
  src/command/subgraph/fetch.rs
  src/command/subgraph/list.rs
  src/command/subgraph/push.rs
  src/utils/stringify.rs
  tests/config/profile.rs
Labels: feature 🎉

#303 Add error for no profiles found (new user)
  crates/houston/src/error.rs
  crates/houston/src/profile/mod.rs
  src/error/metadata/mod.rs
  src/error/metadata/suggestion.rs
  src/error/mod.rs
Labels: feature 🎉

#302 fix(api-key): stop api key printing when written
  crates/houston/src/profile/sensitive.rs
Labels: bug 🐞

#299 feat(rover): output service title for whoami
  crates/rover-client/src/query/config/whoami.graphql
  crates/rover-client/src/query/config/whoami.rs
  src/command/config/whoami.rs
Labels: feature 🎉

#306 fix: s/config/configuration
  crates/houston/src/error.rs
  installers/npm/package-lock.json
Labels: fix 🩹

#307 feat: adds origin to config whoami command
  Cargo.lock
  crates/houston/src/lib.rs
  crates/houston/src/profile/mod.rs
  crates/houston/tests/auth.rs
  crates/rover-client/Cargo.toml
  crates/rover-client/src/blocking/studio_client.rs
  crates/rover-client/src/query/config/whoami.rs
  src/command/config/auth.rs
  src/command/config/whoami.rs
  src/utils/client.rs
Labels: feature 🎉
