Repository apollographql/rover, pull requests merged in 2021-04, with the labels that each got.

#415 More specific and slightly gentler information about the preview period
  docs/source/index.mdx
Labels: docs 📝

#408 feat: displays current version if rover is up to date
  src/utils/version.rs
Labels: feature 🎉

#409 Use Utf8PathBuf::try_from instead of Utf8PathBuf::from_path_buf
  crates/houston/src/config.rs
  crates/houston/src/error.rs
  crates/robot-panic/src/report.rs
  crates/sputnik/src/report.rs
  installers/binstall/src/error.rs
  installers/binstall/src/lib.rs
  installers/binstall/src/system/unix.rs
  src/command/install/mod.rs
  src/command/supergraph/config.rs
  src/error/metadata/mod.rs
  src/utils/loaders.rs
  tests/config/profile.rs
Labels: maintenance 🛠️

#410 chore(rover): adds step to fetch updated tags before a release
  RELEASE_CHECKLIST.md
Labels: maintenance 🛠️

#411 chore(ci): updates actions/cache to v2
  .github/workflows/lint.yml
  .github/workflows/test-nightly.yml
  .github/workflows/test.yml
Labels: maintenance 🛠️

#412 feat: don't display descriptors if output is piped
  src/command/output.rs
Labels: feature 🎉

#413 chore(ci): removes install gnu-tar step
  .github/workflows/release.yml
  .github/workflows/test-nightly.yml
  .github/workflows/test.yml
Labels: maintenance 🛠️

#426 Update install instructions to use a static url
  README.md
  docs/source/ci-cd.md
  docs/source/getting-started.md
Labels: docs 📝

#427 Update telemetry url
  src/utils/telemetry.rs
Labels: maintenance 🛠️

#416 chore(ci): autopublish npm packages
  .github/workflows/release.yml
Labels: maintenance 🛠️

#433 feat: print link to getting started after installation
  installers/npm/install.js
  src/command/install/mod.rs
Labels: feature 🎉

#437 fixup: link to base docs in postinstall
  installers/npm/install.js
  src/command/install/mod.rs
Labels: feature 🎉

#425 Add migration guide from the Apollo CLI -> Rover
  docs/gatsby-config.js
  docs/package-lock.json
  docs/package.json
  docs/source/conventions.md
  docs/source/graphs.md
  docs/source/migration.md
  docs/source/subgraphs.md
  docs/source/supergraphs.md
Labels: docs 📝

#417 chore: adds npm, gh actions, cargo dependabot
  .github/dependabot.yml
Labels: maintenance 🛠️

#442 fix(ci): env.is-prerelease is a string, not a boolean
  .github/workflows/release.yml
Labels: fix 🩹

#448 add triage labels to new issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/docs.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: maintenance 🛠️

#462 fix: prints newline at the end of commands
  src/command/output.rs
Labels: fix 🩹

#470 chore: updates dependencies
  Cargo.lock
Labels: maintenance 🛠️

#472 chore: returns error code for non-200 http status
  crates/rover-client/src/blocking/client.rs
  crates/rover-client/src/blocking/studio_client.rs
  installers/npm/package-lock.json
Labels: feature 🎉

#461 chore(telemetry): report sha-256 of git repo remote URL
  Cargo.lock
  crates/houston/src/error.rs
  crates/sputnik/Cargo.toml
  crates/sputnik/src/error.rs
  crates/sputnik/src/report.rs
  crates/sputnik/src/session.rs
Labels: maintenance 🛠️

#463 chore: more efficient API key load
  crates/houston/src/profile/mod.rs
Labels: maintenance 🛠️

#456 Add telemetry postinstall message
  installers/npm/install.js
  src/command/install/mod.rs
Labels: feature 🎉

#475 Print to file without additional newline
  src/command/output.rs
Labels: fix 🩹

#445 feat: update sha256 section of generated releases
  .github/workflows/release.yml
Labels: feature 🎉
