Repository apollographql/rover, pull requests merged in 2022-11, with the labels that each got.

#1385 feat: report downstream check task results
  crates/rover-client/src/error.rs
  crates/rover-client/src/operations/graph/check_workflow/runner.rs
  crates/rover-client/src/operations/subgraph/check_workflow/check_workflow_query.graphql
  crates/rover-client/src/operations/subgraph/check_workflow/runner.rs
  crates/rover-client/src/shared/check_response.rs
  src/command/output.rs
  src/error/metadata/code.rs
  src/error/metadata/codes/E036.md
  src/error/metadata/codes/E037.md
  src/error/metadata/mod.rs
  src/error/metadata/suggestion.rs
Labels: feature 🎉, 💅 polish

#1396 Add `--skip-update-check` for skipping the once-per-day update check
  src/cli.rs
Labels: feature 🎉

#1377 Add support for polling interval
  src/command/dev/schema.rs
  src/command/dev/watcher.rs
  src/options/subgraph.rs
Labels: feature 🎉

#1392 chore: parallelize supergraph.yaml resolution
  Cargo.lock
  Cargo.toml
  src/command/supergraph/compose/do_compose.rs
  src/command/supergraph/resolve_config.rs
  src/error/metadata/code.rs
  src/error/metadata/codes/E038.md
  src/error/metadata/mod.rs
  src/error/metadata/suggestion.rs
  src/error/mod.rs
  src/utils/emoji.rs
Labels: maintenance 🛠️

#1399 chore: updates rust to 1.65.0
  crates/houston/src/profile/sensitive.rs
  installers/binstall/src/system/unix.rs
  rust-toolchain.toml
  src/command/dev/protocol/leader.rs
  src/command/output.rs
  src/command/supergraph/compose/do_compose.rs
  src/options/template.rs
  src/utils/version.rs
  xtask/src/commands/package/mod.rs
  xtask/src/commands/prep/docs.rs
Labels: maintenance 🛠️

#1404 chore: updates to clap v4
  Cargo.lock
  Cargo.toml
  crates/timber/Cargo.toml
  crates/timber/src/lib.rs
  src/cli.rs
  src/command/config/whoami.rs
  src/command/dev/mod.rs
  src/command/docs/open.rs
  src/command/docs/shortlinks.rs
  src/command/explain.rs
  src/command/fed2/supergraph/compose.rs
  src/command/graph/delete.rs
  src/command/install/mod.rs
  src/command/readme/publish.rs
  src/command/subgraph/delete.rs
  src/command/subgraph/publish.rs
  src/command/supergraph/compose/do_compose.rs
  src/command/template/use.rs
  src/options/check.rs
  src/options/compose.rs
  src/options/graph.rs
  src/options/introspect.rs
  src/options/license.rs
  src/options/profile.rs
  src/options/schema.rs
  src/options/subgraph.rs
  src/options/template.rs
  src/utils/telemetry.rs
  tests/main.rs
  xtask/Cargo.toml
  xtask/src/commands/dist.rs
  xtask/src/commands/docs.rs
  xtask/src/commands/integration_test.rs
  xtask/src/commands/package/macos.rs
  xtask/src/commands/package/mod.rs
  xtask/src/commands/test.rs
  xtask/src/commands/unit_test.rs
  xtask/src/main.rs
  xtask/src/target.rs
Labels: maintenance 🛠️

#1405 chore: updates router and composition versions
  latest_plugin_versions.json
  src/command/dev/mod.rs
Labels: maintenance 🛠️

#1356 chore: prebuilt ARM binaries for linux and macos
  .circleci/config.yml
  Cargo.lock
  Cargo.toml
  README.md
  crates/rover-client/package-lock.json
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/binary.js
  installers/npm/package-lock.json
  installers/npm/package.json
  src/command/install/plugin.rs
  src/error/metadata/suggestion.rs
  xtask/src/commands/dist.rs
  xtask/src/commands/integration_test.rs
  xtask/src/commands/package/mod.rs
  xtask/src/commands/unit_test.rs
  xtask/src/target.rs
  xtask/src/tools/cargo.rs
  xtask/src/tools/mod.rs
  xtask/src/utils.rs
Labels: feature 🎉

#1407 chore: dont use registry url in build-rs
  crates/rover-client/build.rs
Labels: maintenance 🛠️

#1409 docs: document NO_COLOR env var
  docs/source/configuring.md
Labels: docs 📝

#1411 Update to latest client identification headers
  crates/rover-client/build.rs
  crates/rover-client/src/blocking/studio_client.rs
Labels: maintenance 🛠️

#1406 release: v0.10.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  docs/source/ci-cd.md
  docs/source/errors.md
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#1415 chore: use shell-candy to incrementally handle logs
  Cargo.lock
  Cargo.toml
  src/command/dev/command.rs
  src/command/dev/mod.rs
  src/command/dev/router.rs
  xtask/Cargo.toml
  xtask/src/commands/unit_test.rs
  xtask/src/tools/cargo.rs
  xtask/src/tools/git.rs
  xtask/src/tools/make.rs
  xtask/src/tools/npm.rs
  xtask/src/tools/runner.rs
  xtask/src/utils.rs
Labels: maintenance 🛠️

#1418 chore: use crates.io dependencies everywhere
  Cargo.lock
  Cargo.toml
  crates/rover-std/Cargo.toml
  crates/rover-std/src/style.rs
  xtask/Cargo.toml
  xtask/src/main.rs
  xtask/src/utils.rs
Labels: maintenance 🛠️

#1420 feat: adds -n alias for --name for dev
  src/options/subgraph.rs
Labels: feature 🎉

#1428 chore: updates latest federation to 2.2.1
  latest_plugin_versions.json
Labels: maintenance 🛠️

#1442 chore: updates example to apollo server 4 and remove old example
  examples/dev/goodnight/goodnight.js
  examples/dev/goodnight/package-lock.json
  examples/dev/goodnight/package.json
  examples/dev/hello/hello.js
  examples/dev/hello/package-lock.json
  examples/dev/hello/package.json
  examples/dev/maybe/maybe.js
  examples/dev/maybe/package-lock.json
  examples/dev/maybe/package.json
  examples/dev/package-lock.json
  examples/dev/package.json
  examples/dev/reloader/.gitignore
  examples/dev/reloader/package-lock.json
  examples/dev/reloader/package.json
  examples/dev/reloader/reloader.js
  examples/supergraph-demo/package-lock.json
  examples/supergraph-demo/package.json
  examples/supergraph-demo/pandas/package-lock.json
  examples/supergraph-demo/pandas/package.json
  examples/supergraph-demo/pandas/pandas.mjs
  examples/supergraph-demo/products/package
  examples/supergraph-demo/products/package-lock.json
  examples/supergraph-demo/products/package.json
  examples/supergraph-demo/products/products.mjs
  examples/supergraph-demo/users/package-lock.json
  examples/supergraph-demo/users/package.json
  examples/supergraph-demo/users/users.js
  examples/supergraph-demo/users/users.mjs
Labels: maintenance 🛠️
