Repository apollographql/rover, pull requests merged in 2022-08, with the labels that each got.

#1206 chore: removes apollo config
  apollo.config.js
Labels: maintenance 🛠️

#1207 feat: adds --watch to introspect commands
  Cargo.lock
  Cargo.toml
  crates/launchpad/src/blocking/client.rs
  crates/launchpad/src/error.rs
  crates/launchpad/src/introspect/runner.rs
  crates/rover-client/src/blocking/studio_client.rs
  crates/rover-client/src/operations/graph/introspect.rs
  crates/rover-client/src/operations/graph/mod.rs
  crates/rover-client/src/operations/subgraph/introspect/runner.rs
  docs/source/commands/graphs.mdx
  docs/source/commands/subgraphs.mdx
  src/cli.rs
  src/command/graph/introspect.rs
  src/command/graph/mod.rs
  src/command/output.rs
  src/command/subgraph/introspect.rs
  src/command/subgraph/mod.rs
  src/command/supergraph/resolve_config.rs
  src/options/introspect.rs
  src/options/mod.rs
Labels: docs 📝, feature 🎉

#1211 chore: updates xcode from 11.4 to 13.4
  .circleci/config.yml
Labels: maintenance 🛠️

#1216 chore: skip studio tests for forks
  xtask/src/tools/npm.rs
Labels: maintenance 🛠️

#1227 fix: wait for socket to bind before starting supergraph
  src/command/dev/do_dev.rs
  src/command/dev/socket.rs
Labels: fix 🩹

#1229 chore: clean up introspection errors and success
  examples/supergraph-demo/products/package
  src/command/dev/compose.rs
  src/command/dev/introspect.rs
  src/command/dev/router.rs
  src/command/dev/socket.rs
  src/command/dev/watcher.rs
Labels: 💅 polish

#1218 docs: updates help text and refactors subgraph name prompt
  examples/dev/hello/hello.js
  examples/dev/hello/package-lock.json
  src/cli.rs
  src/command/dev/do_dev.rs
  src/command/dev/mod.rs
  src/command/dev/schema.rs
  src/options/subgraph.rs
Labels: docs 📝

#1233 fix(dev): reduce introspection timeouts + spawn/kill process _groups_
  .vscode/changelog.code-snippets
  Cargo.lock
  Cargo.toml
  src/cli.rs
  src/command/dev/command.rs
  src/command/dev/compose.rs
  src/command/dev/do_dev.rs
  src/command/dev/netstat.rs
  src/command/dev/router.rs
  src/command/dev/schema.rs
  src/command/dev/socket.rs
  src/command/dev/watcher.rs
  src/command/graph/mod.rs
  src/command/install/mod.rs
  src/command/subgraph/mod.rs
  src/command/supergraph/compose/do_compose.rs
  src/command/supergraph/resolve_config.rs
  src/utils/client.rs
  src/utils/telemetry.rs
Labels: fix 🩹

#1236 fix: prompt for schema when it is detected
  src/command/dev/schema.rs
  src/utils/mod.rs
Labels: fix 🩹

#1238 fixup: rayon spawn introspectors
  src/command/dev/netstat.rs
Labels: fix 🩹

#1240 chore: removes --command and port scanning
  examples/dev/goodnight/package-lock.json
  examples/dev/goodnight/package.json
  examples/dev/hello/package-lock.json
  examples/dev/hello/package.json
  examples/dev/maybe/package-lock.json
  examples/dev/maybe/package.json
  examples/dev/reloader/package-lock.json
  examples/dev/reloader/package.json
  examples/supergraph-demo/README.md
  examples/supergraph-demo/pandas/package-lock.json
  examples/supergraph-demo/pandas/package.json
  examples/supergraph-demo/products/package-lock.json
  examples/supergraph-demo/products/package.json
  examples/supergraph-demo/users/package-lock.json
  examples/supergraph-demo/users/package.json
  src/command/dev/command.rs
  src/command/dev/do_dev.rs
  src/command/dev/mod.rs
  src/command/dev/netstat.rs
  src/command/dev/router.rs
  src/command/dev/schema.rs
  src/command/dev/socket.rs
Labels: maintenance 🛠️

#1251 chore: updates dependencies
  Cargo.lock
  Cargo.toml
  crates/rover-client/Cargo.toml
  crates/rover-client/src/shared/check_response.rs
  installers/binstall/Cargo.toml
  src/command/output.rs
  xtask/Cargo.toml
Labels: maintenance 🛠️, dependencies

#1264 fix: kill all sessions when main session shuts down
  examples/supergraph-demo/package.json
  src/command/dev/do_dev.rs
  src/command/dev/socket.rs
Labels: fix 🩹

#1271 enable exposing the query plan within `rover dev`
  src/command/dev/router.rs
Labels: feature 🎉

#1268 fix: detect improper VS code pastes on windows
  Cargo.lock
  Cargo.toml
  crates/houston/src/error.rs
  crates/houston/src/profile/sensitive.rs
  installers/binstall/src/system/windows.rs
  src/command/config/auth.rs
  src/error/metadata/code.rs
  src/error/metadata/codes/E035.md
  src/error/metadata/mod.rs
  src/error/metadata/suggestion.rs
Labels: fix 🩹

#1274 feat: allow configurable router downloads
  Cargo.lock
  Cargo.toml
  crates/rover-client/Cargo.toml
  installers/binstall/src/install.rs
  src/command/dev/router.rs
  src/command/install/mod.rs
  src/command/install/plugin.rs
  src/command/supergraph/compose/do_compose.rs
Labels: feature 🎉

#1276 chore: refactors elv2 prompts for rover dev and rover supergraph compose
  crates/houston/src/config.rs
  installers/binstall/src/error.rs
  installers/binstall/src/install.rs
  src/command/dev/do_dev.rs
  src/command/dev/router.rs
  src/command/dev/socket.rs
  src/command/install/mod.rs
  src/command/supergraph/compose/do_compose.rs
  src/options/compose.rs
  src/options/license.rs
  src/options/mod.rs
Labels: fix 🩹

#1279 normalize git remote urls for anonymized telemetry
  Cargo.lock
  crates/sputnik/Cargo.toml
  crates/sputnik/src/session.rs
Labels: fix 🩹
