Repository apollographql/rover, pull requests merged in 2022-09, with the labels that each got.

#1282 feat: composition errors are printed in the session that caused the error
  src/command/dev/compose.rs
  src/command/dev/do_dev.rs
  src/command/dev/follower.rs
  src/command/dev/introspect.rs
  src/command/dev/leader.rs
  src/command/dev/mod.rs
  src/command/dev/netstat.rs
  src/command/dev/protocol.rs
  src/command/dev/router.rs
  src/command/dev/schema.rs
  src/command/dev/socket.rs
  src/command/dev/watcher.rs
  src/command/output.rs
  src/command/supergraph/compose/do_compose.rs
  src/command/supergraph/compose/mod.rs
Labels: feature 🎉, fix 🩹

#1288 chore: updates rover dev versioning strategy
  src/command/dev/command.rs
  src/command/dev/compose.rs
  src/command/dev/do_dev.rs
  src/command/dev/leader.rs
  src/command/dev/mod.rs
  src/command/dev/router.rs
  src/command/supergraph/compose/do_compose.rs
Labels: fix 🩹

#1291 fix: Remove useless stdout for CompositionResult
  src/command/output.rs
Labels: fix 🩹

#1292 chore: updates to rust 1.63.0
  ARCHITECTURE.md
  Cargo.lock
  crates/houston/src/profile/mod.rs
  crates/launchpad/src/introspect/runner.rs
  crates/launchpad/src/introspect/types.rs
  crates/rover-client/src/operations/config/is_federated/runner.rs
  crates/rover-client/src/operations/config/is_federated/types.rs
  crates/rover-client/src/operations/config/who_am_i/runner.rs
  crates/rover-client/src/operations/config/who_am_i/types.rs
  crates/rover-client/src/operations/graph/check/runner.rs
  crates/rover-client/src/operations/graph/check_workflow/runner.rs
  crates/rover-client/src/operations/graph/check_workflow/types.rs
  crates/rover-client/src/operations/graph/delete/runner.rs
  crates/rover-client/src/operations/graph/delete/types.rs
  crates/rover-client/src/operations/graph/fetch/runner.rs
  crates/rover-client/src/operations/graph/fetch/types.rs
  crates/rover-client/src/operations/graph/publish/runner.rs
  crates/rover-client/src/operations/graph/publish/types.rs
  crates/rover-client/src/operations/graph/variant/runner.rs
  crates/rover-client/src/operations/graph/variant/types.rs
  crates/rover-client/src/operations/readme/fetch/runner.rs
  crates/rover-client/src/operations/readme/fetch/types.rs
  crates/rover-client/src/operations/readme/publish/runner.rs
  crates/rover-client/src/operations/readme/publish/types.rs
  crates/rover-client/src/operations/subgraph/check/runner.rs
  crates/rover-client/src/operations/subgraph/check_workflow/runner.rs
  crates/rover-client/src/operations/subgraph/check_workflow/types.rs
  crates/rover-client/src/operations/subgraph/delete/runner.rs
  crates/rover-client/src/operations/subgraph/delete/types.rs
  crates/rover-client/src/operations/subgraph/fetch/runner.rs
  crates/rover-client/src/operations/subgraph/fetch/types.rs
  crates/rover-client/src/operations/subgraph/introspect/runner.rs
  crates/rover-client/src/operations/subgraph/introspect/types.rs
  crates/rover-client/src/operations/subgraph/list/runner.rs
  crates/rover-client/src/operations/subgraph/list/types.rs
  crates/rover-client/src/operations/subgraph/publish/runner.rs
  crates/rover-client/src/operations/subgraph/publish/types.rs
  crates/rover-client/src/operations/supergraph/fetch/runner.rs
  crates/rover-client/src/operations/supergraph/fetch/types.rs
  crates/rover-client/src/shared/async_check_response.rs
  crates/rover-client/src/shared/check_response.rs
  crates/rover-client/src/shared/fetch_response.rs
  crates/rover-client/src/shared/git_context.rs
  crates/rover-client/src/shared/graph_ref.rs
  crates/sputnik/src/session.rs
  installers/binstall/src/system/unix.rs
  rust-toolchain.toml
  src/cli.rs
  src/command/graph/introspect.rs
  src/command/subgraph/introspect.rs
  src/command/supergraph/compose/do_compose.rs
  src/utils/parsers.rs
  xtask/src/tools/cargo.rs
  xtask/src/tools/git.rs
  xtask/src/tools/strip.rs
Labels: maintenance 🛠️

#1303 chore: s/launchpad/introspector-gadget
  Cargo.lock
  Cargo.toml
  crates/launchpad/Cargo.toml
  crates/launchpad/README.md
  crates/launchpad/src/blocking/client.rs
  crates/launchpad/src/blocking/mod.rs
  crates/launchpad/src/error.rs
  crates/launchpad/src/introspect/fixtures/interfaces.json
  crates/launchpad/src/introspect/fixtures/simple.json
  crates/launchpad/src/introspect/fixtures/swapi.json
  crates/launchpad/src/introspect/introspect_query.graphql
  crates/launchpad/src/introspect/introspect_schema.graphql
  crates/launchpad/src/introspect/mod.rs
  crates/launchpad/src/introspect/runner.rs
  crates/launchpad/src/introspect/schema.rs
  crates/launchpad/src/introspect/types.rs
  crates/launchpad/src/lib.rs
  crates/rover-client/Cargo.toml
  crates/rover-client/src/blocking/mod.rs
  crates/rover-client/src/error.rs
  crates/rover-client/src/operations/graph/introspect.rs
Labels: maintenance 🛠️

#1313 fix: too many open files error
  Cargo.lock
  Cargo.toml
  src/command/dev/leader.rs
  src/command/dev/protocol.rs
Labels: fix 🩹

#1317 feat: adds emojis to rover dev
  src/options/subgraph.rs
  src/utils/emoji.rs
  src/utils/mod.rs
Labels: 💅 polish

#1319 fix: use channel instead of socket for main `rover dev` session
  .cargo/config
  Cargo.lock
  Cargo.toml
  src/command/dev/compose.rs
  src/command/dev/do_dev.rs
  src/command/dev/follower.rs
  src/command/dev/leader.rs
  src/command/dev/mod.rs
  src/command/dev/protocol/follower/message.rs
  src/command/dev/protocol/follower/messenger.rs
  src/command/dev/protocol/follower/mod.rs
  src/command/dev/protocol/leader.rs
  src/command/dev/protocol/mod.rs
  src/command/dev/protocol/socket.rs
  src/command/dev/protocol/types.rs
  src/command/dev/router.rs
  src/command/dev/schema.rs
  src/command/dev/watcher.rs
  src/utils/emoji.rs
Labels: fix 🩹

#1307 chore: use --dev mode for router
  src/command/dev/mod.rs
  src/command/dev/protocol/leader.rs
  src/command/dev/router.rs
Labels: maintenance 🛠️

#1321 feat: quiet router logs and port/ip assigning
  Cargo.lock
  Cargo.toml
  examples/supergraph-demo/products/.products.graphql.swp
  examples/supergraph-demo/products/products.graphql
  src/command/dev/command.rs
  src/command/dev/compose.rs
  src/command/dev/do_dev.rs
  src/command/dev/mod.rs
  src/command/dev/protocol/leader.rs
  src/command/dev/router.rs
  src/command/supergraph/compose/do_compose.rs
  src/utils/emoji.rs
Labels: feature 🎉, 💅 polish

#1322 fix: disallow same URL and small copy updates
  examples/supergraph-demo/products/.products.graphql.swp
  src/command/dev/netstat.rs
  src/command/dev/schema.rs
  src/options/subgraph.rs
Labels: fix 🩹, 💅 polish

#1325 fix: cleans up various error messages and suggestions
  crates/rover-client/src/blocking/studio_client.rs
  crates/rover-client/src/error.rs
  crates/rover-client/src/releases.rs
  docs/source/errors.md
  src/command/dev/compose.rs
  src/command/dev/introspect.rs
  src/command/dev/protocol/follower/message.rs
  src/command/dev/protocol/leader.rs
  src/command/output.rs
  src/command/supergraph/compose/do_compose.rs
  src/error/metadata/mod.rs
  src/error/metadata/suggestion.rs
Labels: fix 🩹

#1327 chore: Try to further simplify templates stuff
  src/command/template/list.rs
  src/command/template/templates.rs
  src/command/template/use.rs
  src/options/template.rs
Labels: maintenance 🛠️

#1326 feat: prompt for `<PATH>` if it's not specified
  Cargo.lock
  Cargo.toml
  crates/houston/Cargo.toml
  crates/robot-panic/Cargo.toml
  crates/rover-client/Cargo.toml
  crates/sputnik/Cargo.toml
  installers/binstall/Cargo.toml
  src/command/output.rs
  src/command/template/list.rs
  src/command/template/mod.rs
  src/command/template/templates.rs
  src/command/template/use.rs
  src/options/template.rs
  xtask/Cargo.toml
Labels: feature 🎉

#1329 chore: updates router and adds env var escape hatches
  Cargo.lock
  Cargo.toml
  src/command/dev/mod.rs
  src/command/dev/protocol/leader.rs
  src/command/dev/router.rs
Labels: maintenance 🛠️

#1330 chore: updates to process terminology used by docs
  examples/supergraph-demo/README.md
  src/command/dev/do_dev.rs
  src/command/dev/mod.rs
  src/command/dev/protocol/follower/message.rs
  src/command/dev/protocol/follower/messenger.rs
  src/command/dev/protocol/leader.rs
  src/options/subgraph.rs
Labels: maintenance 🛠️

#1323 docs: initial rover dev
  docs/source/_redirects
  docs/source/commands/dev.mdx
  docs/source/config.json
  docs/source/configuring.md
  docs/source/index.mdx
  src/command/dev/protocol/follower/message.rs
  src/utils/emoji.rs
Labels: docs 📝

#1287 feat: `rover template`
  Cargo.lock
  Cargo.toml
  crates/houston/Cargo.toml
  crates/robot-panic/Cargo.toml
  crates/rover-client/Cargo.toml
  crates/sputnik/Cargo.toml
  docs/source/_redirects
  docs/source/commands/template.mdx
  docs/source/config.json
  installers/binstall/Cargo.toml
  src/cli.rs
  src/command/mod.rs
  src/command/output.rs
  src/command/template/list.rs
  src/command/template/mod.rs
  src/command/template/templates.rs
  src/command/template/use.rs
  src/options/mod.rs
  src/options/template.rs
  src/utils/emoji.rs
  xtask/Cargo.toml
Labels: feature 🎉

#1332 chore: address gateway copy issues
  docs/source/commands/subgraphs.mdx
  docs/source/commands/supergraphs.mdx
  src/command/output.rs
  src/command/subgraph/publish.rs
Labels: 💅 polish

#1340 s/port/supergraph-port
  src/command/dev/do_dev.rs
  src/command/dev/protocol/leader.rs
Labels: fix 🩹

#1343 fix: don't print error of startup socket read
  src/command/dev/protocol/leader.rs
Labels: fix 🩹

#1344 chore: specify all dependencies in root Cargo.toml
  Cargo.lock
  Cargo.toml
  crates/houston/Cargo.toml
  crates/robot-panic/Cargo.toml
  crates/rover-client/Cargo.toml
  crates/sputnik/Cargo.toml
  crates/timber/Cargo.toml
  rust-toolchain.toml
  xtask/Cargo.toml
Labels: maintenance 🛠️

#1346 chore: updates dependencies
  Cargo.lock
  Cargo.toml
  crates/rover-client/Cargo.toml
  crates/rover-client/build.rs
Labels: maintenance 🛠️

#1351 chore: cache ~/.cargo in CI
  .circleci/config.yml
Labels: maintenance 🛠️

#1352 chore: restore cache before installing rust
  .circleci/config.yml
Labels: maintenance 🛠️

#1347 feat: Add templates for TypeScript, Go, Kotlin, and Java
  src/command/template/templates.rs
  src/options/template.rs
Labels: feature 🎉

#1357 fix: install plugins before creating leader session
  src/command/dev/compose.rs
  src/command/dev/protocol/leader.rs
  src/command/supergraph/compose/do_compose.rs
Labels: fix 🩹

#1358 chore: fix typo in subgraph publish output
  crates/rover-client/src/operations/subgraph/publish/runner.rs
  src/command/output.rs
Labels: fix 🩹

#1350 chore: dont exclude certain git remotes
  crates/rover-client/src/shared/git_context.rs
Labels: fix 🩹

#1359 release: v0.9.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  crates/rover-client/package-lock.json
  docs/source/ci-cd.md
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release
