Repository apollographql/rover, pull requests merged in 2022-02, with the labels that each got.

#988 fix(rover-client): introspection result should omit Float scalar
  crates/rover-client/src/operations/graph/introspect/fixtures/interfaces.json
  crates/rover-client/src/operations/graph/introspect/schema.rs
Labels: bug 🐞

#990 chore: lower the max glibc version to 2.17
  check_glibc.sh
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/nix/install_rover_fed2.sh
  installers/npm/binary.js
  src/error/metadata/suggestion.rs
Labels: fix 🩹

#996 chore: updates dependencies
  Cargo.lock
  Cargo.toml
  crates/rover-client/Cargo.toml
  crates/rover-client/src/blocking/client.rs
  xtask/Cargo.toml
Labels: maintenance 🛠️

#999 chore: support node 17 in rover installer
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: maintenance 🛠️

#1016 chore: replace README badges.
  README.md
Labels: maintenance 🛠️
