Repository apollographql/rover, pull requests merged in 2022-07, with the labels that each got.

#1166 chore: improves schema downloading and debugging
  crates/launchpad/src/blocking/client.rs
  crates/rover-client/build.rs
Labels: maintenance 🛠️

#1188 chore: adds Apollo Studio integration tests
  .cargo/config
  .circleci/config.yml
  .gitignore
  examples/README.md
  examples/flyby/.gitignore
  examples/flyby/README.md
  examples/flyby/package-lock.json
  examples/flyby/package.json
  examples/flyby/rover.js
  examples/flyby/subgraphs/locations.graphql
  examples/flyby/subgraphs/reviews.graphql
  examples/flyby/supergraphs/file.yaml
  examples/flyby/supergraphs/flyby.graphql
  examples/flyby/supergraphs/graphref.yaml
  examples/flyby/supergraphs/introspect.yaml
  xtask/src/commands/integration_test.rs
  xtask/src/tools/npm.rs
Labels: maintenance 🛠️

#1184 Install rover before run if missing
  installers/npm/binary.js
  installers/npm/package-lock.json
  installers/npm/package.json
  installers/npm/run.js
Labels: maintenance 🛠️

#1176 docs: update anchors for fetching schema
  docs/source/commands/graphs.mdx
Labels: docs 📝

#1196 fix(ci): checkout code before installing deps
  .circleci/config.yml
Labels: fix 🩹

#1193 docs: adds async checks docs
  docs/source/ci-cd.md
  docs/source/commands/graphs.mdx
  docs/source/commands/subgraphs.mdx
Labels: docs 📝

#1202 use more specific URL for obtaining "Personal API Key"
  CHANGELOG.md
  apollo.config.js
  docs/source/commands/config.mdx
  src/command/config/auth.rs
Labels: feature 🎉
