Repository apollographql/rover, pull requests merged in 2023-12, with the labels that each got.

#1798 fix(rover-client): fix unmatched typenames
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/src/error.rs
  crates/rover-client/src/operations/graph/check/runner.rs
  crates/rover-client/src/operations/subgraph/check/runner.rs
  src/error/metadata/mod.rs
  src/error/metadata/suggestion.rs
Labels: fix 🩹

#1802 release: v0.22.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  RELEASE_CHECKLIST.md
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/package-lock.json
  docs/source/ci-cd.mdx
  docs/source/errors.md
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#1803 chore: Remove yanked online check
  Cargo.lock
  Cargo.toml
  xtask/Cargo.toml
  xtask/src/commands/prep/main_schema.rs
  xtask/src/commands/prep/mod.rs
  xtask/src/commands/prep/templates_schema.rs
Labels: maintenance 🛠️
