Repository apollographql/rover, pull requests merged in 2023-05, with the labels that each got.

#1595 chore: runs `cargo update`
  Cargo.lock
  examples/supergraph-demo/resolved.yaml
  examples/supergraph-demo/supergraph.yaml
  examples/supergraph-demo/users/users.graphql
Labels: maintenance 🛠️

#1597 release: v0.14.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  docs/source/ci-cd.md
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#1598 Abstract out auth notice in docs
  docs/shared/auth-notice.mdx
  docs/source/commands/contracts.mdx
  docs/source/commands/graphs.mdx
  docs/source/commands/readmes.mdx
  docs/source/commands/subgraphs.mdx
  docs/source/commands/supergraphs.mdx
Labels: docs 📝

#1607 fix: Don't panic when Router does not start in `rover dev`
  src/command/dev/protocol/leader.rs
  src/command/dev/router/runner.rs
Labels: fix 🩹

#1608 fix: `rover dev` when used with Enterprise features
  src/command/dev/router/command.rs
  src/command/dev/router/runner.rs
Labels: fix 🩹

#1618 chore: updates dependencies
  Cargo.lock
  Cargo.toml
  crates/rover-client/src/operations/subgraph/check_workflow/runner.rs
  crates/rover-client/src/operations/subgraph/delete/runner.rs
  crates/rover-client/src/operations/subgraph/publish/runner.rs
  crates/rover-client/src/operations/supergraph/fetch/runner.rs
  installers/binstall/Cargo.toml
  src/command/output.rs
  src/utils/mod.rs
  xtask/Cargo.toml
Labels: maintenance 🛠️, :christmas_tree: dependencies
