Repository apollographql/rover, pull requests merged in 2023-04, with the labels that each got.

#1568 Move old CLI docs to Rover docset
  docs/source/apollo-cli.mdx
  docs/source/config.json
  docs/source/migration.md
Labels: docs 📝

#1573 Update old links for new docsite
  docs/source/ci-cd.md
  docs/source/commands/graphs.mdx
  docs/source/commands/readmes.mdx
  docs/source/commands/subgraphs.mdx
  docs/source/commands/supergraphs.mdx
  docs/source/conventions.md
Labels: docs 📝

#1575 fix: removes duplicated `IsFederatedQuery` and allows `--convert`
  crates/rover-client/src/operations/subgraph/routing_url/runner.rs
Labels: fix 🩹

#1565 feat: warn when `--routing-url` is unroutable
  .gitignore
  crates/rover-client/src/error.rs
  crates/rover-client/src/operations/subgraph/mod.rs
  crates/rover-client/src/operations/subgraph/routing_url/mod.rs
  crates/rover-client/src/operations/subgraph/routing_url/routing_url_query.graphql
  crates/rover-client/src/operations/subgraph/routing_url/runner.rs
  crates/rover-client/src/operations/subgraph/routing_url/types.rs
  src/command/subgraph/publish.rs
  src/error/metadata/code.rs
  src/error/metadata/codes/E041.md
  src/error/metadata/mod.rs
  src/error/metadata/suggestion.rs
Labels: feature 🎉

#1574 feat: Allow custom headers when introspecting in `supergraph compose`
  Cargo.lock
  Cargo.toml
  docs/source/commands/supergraphs.mdx
  src/command/supergraph/resolve_config.rs
  src/utils/expansion.rs
  src/utils/mod.rs
Labels: feature 🎉

#1581 release: v0.14.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  docs/source/ci-cd.md
  docs/source/errors.md
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release
