Repository apollographql/rover, pull requests merged in 2023-09, with the labels that each got.

#1743 chore: don't issue head request to determine version unless plugin is latest
  Cargo.lock
  installers/binstall/Cargo.toml
  installers/binstall/src/install.rs
  src/command/install/plugin.rs
Labels: maintenance 🛠️

#1727 feat: allow publishing PQs from relay compiler via new `--manifest-format` argument
  Cargo.lock
  crates/rover-client/Cargo.toml
  crates/rover-client/src/error.rs
  crates/rover-client/src/operations/persisted_queries/publish/mod.rs
  crates/rover-client/src/operations/persisted_queries/publish/types.rs
  crates/rover-client/src/shared/check_response.rs
  crates/rover-client/src/shared/lint_response.rs
  docs/source/commands/persisted-queries.mdx
  src/command/persisted_queries/publish.rs
  src/error/metadata/mod.rs
  src/options/mod.rs
  src/options/persisted_queries.rs
Labels: feature 🎉

#1747 fix: don't output color when writing to files via --output or via unix pipe
  Cargo.lock
  Cargo.toml
  crates/rover-client/src/shared/lint_response.rs
  crates/rover-std/Cargo.toml
  crates/rover-std/src/lib.rs
  crates/rover-std/src/output.rs
  crates/rover-std/src/style.rs
  installers/binstall/Cargo.toml
  installers/binstall/src/install.rs
  src/command/output.rs
  src/command/subgraph/publish.rs
  src/command/template/use.rs
  src/options/license.rs
  src/options/output.rs
  src/options/subgraph.rs
Labels: fix 🩹

#1748 release: v0.19.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  docs/source/ci-cd.md
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#1750 fix: point lint diagnostics to the right place when using unicode
  Cargo.lock
  Cargo.toml
  crates/rover-client/Cargo.toml
  crates/rover-client/src/shared/lint_response.rs
Labels: fix 🩹

#1751 chore: updates rust to 1.72.0 and addresses new lints
  installers/binstall/src/system/unix.rs
  rust-toolchain.toml
  src/command/subgraph/publish.rs
  xtask/src/commands/prep/installers.rs
Labels: maintenance 🛠️

#1753 release: v0.19.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  docs/source/ci-cd.md
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
  rust-toolchain.toml
Labels: 🚢 release
