Repository apollographql/rover, pull requests merged in 2023-02, with the labels that each got.

#1504 release: v0.11.1 (#1504
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  docs/source/ci-cd.md
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#1505 chore: fix up test runner (#1505
  xtask/src/tools/cargo.rs
Labels: maintenance 🛠️

#1490 Support check workflows with no operation check
  crates/rover-client/src/error.rs
  crates/rover-client/src/operations/graph/check_workflow/runner.rs
  crates/rover-client/src/operations/subgraph/check_workflow/runner.rs
  crates/rover-client/src/shared/check_response.rs
  crates/rover-client/src/shared/mod.rs
  src/command/graph/check.rs
  src/command/output.rs
Labels: feature 🎉

#1516 release: v0.12.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  docs/source/ci-cd.md
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#1517 docs: fix up some rover dev docs
  docs/source/commands/dev.mdx
Labels: docs 📝

#1520 release: v0.12.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/package-lock.json
  docs/source/ci-cd.md
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#1525 fix: allow checks to fail from composition (#1525
  crates/rover-client/src/operations/subgraph/check_workflow/runner.rs
Labels: fix 🩹

#1524 feat: warn when version isn't pinned
  docs/source/commands/supergraphs.mdx
  examples/supergraph-demo/supergraph.yaml
  src/command/supergraph/resolve_config.rs
Labels: feature 🎉
