Repository apollographql/rover, pull requests merged in 2023-10, with the labels that each got.

#1757 Show a better message when a subgraph is published with no changes
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/src/operations/subgraph/publish/publish_mutation.graphql
  crates/rover-client/src/operations/subgraph/publish/runner.rs
  crates/rover-client/src/operations/subgraph/publish/types.rs
  docs/source/configuring.md
  src/command/output.rs
Labels: fix 🩹

#1758 fix: don't log username/password in binary mirror proxy URLs
  Cargo.lock
  crates/rover-std/Cargo.toml
  crates/rover-std/src/lib.rs
  crates/rover-std/src/url.rs
  src/command/install/plugin.rs
Labels: fix 🩹

#1763 release: v0.20.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/package-lock.json
  docs/source/ci-cd.md
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#1770 chore: updates rust to 1.73.0
  rust-toolchain.toml
  src/command/output.rs
Labels: maintenance 🛠️

#1774 docs: Add HotChocolate template
  docs/source/commands/template.mdx
Labels: docs 📝

#1768 feat: Include ProposalsCheckTask in the check workflow response
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/src/error.rs
  crates/rover-client/src/operations/graph/check_workflow/runner.rs
  crates/rover-client/src/operations/subgraph/check_workflow/check_workflow_query.graphql
  crates/rover-client/src/operations/subgraph/check_workflow/runner.rs
  crates/rover-client/src/operations/subgraph/check_workflow/types.rs
  crates/rover-client/src/shared/check_response.rs
  crates/rover-client/src/shared/mod.rs
  src/command/output.rs
Labels: feature 🎉

#1776 release: 0.21.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/package-lock.json
  docs/source/ci-cd.md
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release
