Repository apollographql/rover, pull requests merged in 2023-06, with the labels that each got.

#1599 feat: `rover persisted-queries publish`
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  crates/rover-client/src/error.rs
  crates/rover-client/src/operations/mod.rs
  crates/rover-client/src/operations/persisted_queries/describe_pql/describe_pql_query.graphql
  crates/rover-client/src/operations/persisted_queries/describe_pql/mod.rs
  crates/rover-client/src/operations/persisted_queries/describe_pql/runner.rs
  crates/rover-client/src/operations/persisted_queries/describe_pql/types.rs
  crates/rover-client/src/operations/persisted_queries/mod.rs
  crates/rover-client/src/operations/persisted_queries/publish/mod.rs
  crates/rover-client/src/operations/persisted_queries/publish/publish_mutation.graphql
  crates/rover-client/src/operations/persisted_queries/publish/runner.rs
  crates/rover-client/src/operations/persisted_queries/publish/types.rs
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
  src/cli.rs
  src/command/mod.rs
  src/command/output.rs
  src/command/persisted_queries/mod.rs
  src/command/persisted_queries/publish.rs
  src/error/metadata/mod.rs
  src/error/metadata/suggestion.rs
  src/options/graph.rs
Labels: feature 🎉

#1628 release: v0.15.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  docs/source/ci-cd.md
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#1627 feat: Support `supergraph.yml` for `rover dev`
  docs/source/commands/dev.mdx
  src/command/dev/do_dev.rs
  src/command/dev/introspect.rs
  src/command/dev/mod.rs
  src/command/dev/protocol/follower/message.rs
  src/command/dev/protocol/follower/messenger.rs
  src/command/dev/router/runner.rs
  src/command/dev/schema.rs
  src/command/dev/watcher.rs
  src/command/supergraph/mod.rs
  tests/dev/arg_conflicts.rs
  tests/dev/mod.rs
  tests/main.rs
Labels: feature 🎉

#1620 feat: `rover graph lint` and `rover subgraph lint`
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/Cargo.toml
  crates/rover-client/package-lock.json
  crates/rover-client/src/error.rs
  crates/rover-client/src/operations/graph/lint/lint_graph_mutation.graphql
  crates/rover-client/src/operations/graph/lint/mod.rs
  crates/rover-client/src/operations/graph/lint/runner.rs
  crates/rover-client/src/operations/graph/lint/types.rs
  crates/rover-client/src/operations/graph/mod.rs
  crates/rover-client/src/operations/subgraph/lint/lint_subgraph_mutation.graphql
  crates/rover-client/src/operations/subgraph/lint/mod.rs
  crates/rover-client/src/operations/subgraph/lint/runner.rs
  crates/rover-client/src/operations/subgraph/lint/types.rs
  crates/rover-client/src/operations/subgraph/mod.rs
  crates/rover-client/src/shared/lint_response.rs
  crates/rover-client/src/shared/mod.rs
  crates/rover-std/src/lib.rs
  crates/rover-std/src/style.rs
  docs/source/commands/graphs.mdx
  docs/source/commands/subgraphs.mdx
  docs/source/errors.md
  src/command/graph/lint.rs
  src/command/graph/mod.rs
  src/command/output.rs
  src/command/subgraph/lint.rs
  src/command/subgraph/mod.rs
  src/error/metadata/code.rs
  src/error/metadata/codes/E042.md
  src/error/metadata/mod.rs
  src/error/metadata/suggestion.rs
  src/error/mod.rs
  src/options/lint.rs
  src/options/mod.rs
  src/options/schema.rs
Labels: feature 🎉

#1642 release: v0.16.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/package-lock.json
  docs/source/ci-cd.md
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#1652 fix: YAML federation version by updating apollo-federation-types
  Cargo.lock
  Cargo.toml
  src/command/supergraph/resolve_config.rs
Labels: fix 🩹

#1653 release: v0.16.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  docs/source/ci-cd.md
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#1656 release: v0.16.2
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/package-lock.json
  docs/source/ci-cd.md
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#1658 fix: use notarytool instead of altool to codesign macos binaries
  Cargo.lock
  xtask/src/commands/package/macos.rs
  xtask/src/tools/mod.rs
  xtask/src/tools/runner.rs
  xtask/src/tools/xcrun.rs
Labels: maintenance 🛠️, fix 🩹
