Repository apollographql/rover, pull requests merged in 2023-01, with the labels that each got.

#1456 Improve handling of license flag
  src/options/license.rs
Labels: 💅 polish

#1446 feat: adds '--router-config' to 'rover dev'
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  crates/rover-std/Cargo.toml
  crates/rover-std/src/fs.rs
  docs/source/commands/dev.mdx
  examples/supergraph-demo/pandas/package-lock.json
  examples/supergraph-demo/products/package-lock.json
  examples/supergraph-demo/users/package-lock.json
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
  src/command/dev/do_dev.rs
  src/command/dev/mod.rs
  src/command/dev/protocol/follower/mod.rs
  src/command/dev/protocol/leader.rs
  src/command/dev/router/command.rs
  src/command/dev/router/config.rs
  src/command/dev/router/mod.rs
  src/command/dev/router/runner.rs
  src/command/dev/watcher.rs
  src/options/subgraph.rs
Labels: feature 🎉

#1478 fix: make --watch work with new --output
  docs/source/commands/graphs.mdx
  docs/source/commands/readmes.mdx
  docs/source/commands/subgraphs.mdx
  docs/source/commands/supergraphs.mdx
  docs/source/conventions.md
  docs/source/migration.md
  src/cli.rs
  src/command/graph/introspect.rs
  src/command/graph/mod.rs
  src/command/output.rs
  src/command/subgraph/introspect.rs
  src/command/subgraph/mod.rs
  src/error/metadata/mod.rs
  src/error/mod.rs
  src/options/introspect.rs
  src/options/output.rs
Labels: fix 🩹, 💅 polish

#1413 chore(cli): change name of --output option to --format
  CHANGELOG.md
  README.md
  crates/rover-std/src/emoji.rs
  docs/source/commands/graphs.mdx
  docs/source/commands/readmes.mdx
  docs/source/commands/subgraphs.mdx
  docs/source/commands/supergraphs.mdx
  docs/source/configuring.md
  docs/source/conventions.md
  docs/source/migration.md
  src/bin/rover.rs
  src/cli.rs
  src/command/graph/introspect.rs
  src/command/graph/mod.rs
  src/command/output.rs
  src/command/subgraph/delete.rs
  src/command/subgraph/introspect.rs
  src/command/subgraph/mod.rs
  src/error/metadata/mod.rs
  src/error/mod.rs
  src/options/introspect.rs
  src/options/mod.rs
  src/options/output.rs
Labels: feature 🎉

#1479 hotfix: resolve merge conflicts between `main` and `sachin/new-contracts-commands`
  CHANGELOG.md
  README.md
  crates/rover-std/src/emoji.rs
  docs/source/commands/graphs.mdx
  docs/source/commands/readmes.mdx
  docs/source/commands/subgraphs.mdx
  docs/source/commands/supergraphs.mdx
  docs/source/configuring.md
  docs/source/conventions.md
  docs/source/migration.md
  src/bin/rover.rs
  src/cli.rs
  src/command/graph/introspect.rs
  src/command/graph/mod.rs
  src/command/output.rs
  src/command/subgraph/delete.rs
  src/command/subgraph/introspect.rs
  src/command/subgraph/mod.rs
  src/error/metadata/mod.rs
  src/error/mod.rs
  src/options/introspect.rs
  src/options/mod.rs
  src/options/output.rs
Labels: maintenance 🛠️

#1480 chore: create router config if one doesn't exist
  crates/rover-std/src/emoji.rs
  crates/rover-std/src/fs.rs
  src/command/dev/router/config.rs
Labels: fix 🩹

#1481 chore: updates dependencies
  Cargo.lock
  Cargo.toml
  xtask/src/commands/package/macos.rs
Labels: maintenance 🛠️

#1482 release: v0.11.0-rc.2
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/package-lock.json
  docs/source/config.json
  docs/source/errors.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
  xtask/src/commands/package/macos.rs
Labels: docs 📝, 🚢 release

#1485 chore: simplifies warning copy
  src/options/output.rs
Labels: 💅 polish

#1483 chore: clean up xtask
  .circleci/config.yml
  Cargo.lock
  Cargo.toml
  xtask/Cargo.toml
  xtask/src/commands/dist.rs
  xtask/src/commands/docs.rs
  xtask/src/commands/integration_test.rs
  xtask/src/commands/lint.rs
  xtask/src/commands/package/mod.rs
  xtask/src/commands/prep/mod.rs
  xtask/src/commands/test.rs
  xtask/src/commands/unit_test.rs
  xtask/src/main.rs
  xtask/src/tools/cargo.rs
  xtask/src/tools/git.rs
  xtask/src/tools/lychee.rs
  xtask/src/tools/make.rs
  xtask/src/tools/mod.rs
  xtask/src/tools/npm.rs
  xtask/src/tools/runner.rs
Labels: maintenance 🛠️
