Repository apollographql/rover, pull requests merged in 2023-08, with the labels that each got.

#1695 release: v0.17.3
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/package-lock.json
  docs/source/ci-cd.md
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#1705 fix: Update error code for check failure
  docs/source/errors.md
  src/command/output.rs
  src/error/metadata/code.rs
  src/error/metadata/codes/E043.md
  src/error/metadata/mod.rs
Labels: fix 🩹

#1698 [docs] Add persisted-queries command
  docs/source/commands/persisted-queries.mdx
  docs/source/config.json
  src/cli.rs
Labels: docs 📝

#1706 feat(breaking): prevent publishing unparseable routing URLs without explicit flag
  docs/source/commands/subgraphs.mdx
  src/command/subgraph/publish.rs
  src/error/metadata/suggestion.rs
Labels: feature 🎉, BREAKING :exclamation:

#1708 release: v0.18.0
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  docs/source/ci-cd.md
  docs/source/errors.md
  docs/source/getting-started.md
Labels: BREAKING :exclamation:, 🚢 release

#1713 feat(install): plugins support APOLLO_ROVER_DOWNLOAD_HOST
  docs/source/getting-started.md
  src/command/install/plugin.rs
Labels: feature 🎉

#1716 docs: clearer docs for plugin download host configuration
  docs/source/getting-started.md
Labels: docs 📝

#1719 fixup: re-add .npmrc note
  docs/source/getting-started.md
Labels: docs 📝

#1718 chore: install volta via chocolatey instead of flaky MSI installer
  .circleci/config.yml
Labels: maintenance 🛠️

#1715 docs(telemetry): update instructions for disabling telemetry
  docs/source/configuring.md
  docs/source/privacy.mdx
  installers/npm/binary.js
  src/utils/telemetry.rs
Labels: docs 📝

#1726 release: v0.18.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  docs/source/ci-cd.md
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release
