Repository apollographql/rover, pull requests merged in 2023-03, with the labels that each got.

#1536 fix: don't squash supergraph router config (#1536
  Cargo.lock
  examples/supergraph-demo/router.yaml
  src/command/dev/protocol/leader.rs
  src/command/dev/router/config.rs
  src/command/dev/router/runner.rs
Labels: fix 🩹

#1388 feat: Fetch templates from a GraphQL API (#1388)Co-authored-by: Dylan Anthony <dbanty@users.noreply.github.com> Co-authored-by: Avery Harnish <avery@apollographql.com>
  .gitignore
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/last_run.uuid
  src/command/mod.rs
  src/command/output.rs
  src/command/template/.gitignore
  src/command/template/custom_scalars.rs
  src/command/template/list.rs
  src/command/template/mod.rs
  src/command/template/queries.graphql
  src/command/template/queries.rs
  src/command/template/templates.rs
  src/command/template/use.rs
  src/options/template.rs
  xtask/Cargo.toml
  xtask/src/commands/prep/main_schema.rs
  xtask/src/commands/prep/mod.rs
  xtask/src/commands/prep/templates_schema.rs
Labels: feature 🎉

#1539 release: v0.13.0 (#1539)Co-authored-by: Dylan Anthony <dbanty@users.noreply.github.com>
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  RELEASE_CHECKLIST.md
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/package-lock.json
  docs/source/ci-cd.md
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#1542 docs: Mention community-maintained installation methods
  docs/source/getting-started.md
Labels: docs 📝

#1548 fix: `std::thread::spawn` the subgraph watcher instead of rayon
  src/command/dev/do_dev.rs
Labels: fix 🩹

#1557 chore: update macos runners to large m1
  .circleci/config.yml
Labels: maintenance 🛠️
