Repository apollographql/rover, pull requests merged in 2024-09, with the labels that each got.

#2045 feat(compose): when `--output` is used, use `--output` in supergraph bin
  src/cli.rs
  src/command/dev/compose.rs
  src/command/supergraph/compose/do_compose.rs
  src/command/supergraph/compose/no_compose.rs
  src/command/supergraph/mod.rs
  src/options/output.rs
  src/utils/supergraph_config.rs
Labels: feature 🎉

#2097 release: v0.26.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/package-lock.json
  docs/source/ci-cd.mdx
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#2114 docs: fix glossary links
  docs/source/commands/graphs.mdx
  docs/source/commands/subgraphs.mdx
Labels: docs 📝

#2116 release: v0.26.2
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  docs/source/ci-cd.mdx
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#2119 ROVER-135 Make paths in supergraph.yaml resolve relative to the location of the file, not the current working directory of Rover
  Cargo.lock
  Cargo.toml
  src/error/metadata/suggestion.rs
  src/utils/supergraph_config.rs
  src/utils/telemetry.rs
Labels: feature 🎉, BREAKING :exclamation:
