Repository apollographql/rover, pull requests merged in 2024-07, with the labels that each got.

#1967 Fix `package.json` to a stable version when testing NPM installers
  .circleci/scripts/install_npm.sh
  .circleci/scripts/install_npm_global.sh
  .circleci/scripts/install_pnpm.sh
Labels: fix 🩹

#1968 Move mock to the highest level of the tests
  installers/npm/tests/binary.test.js
Labels: fix 🩹

#1956 fix(dev): intermediate composition states have noisy errors
  src/command/dev/protocol/leader.rs
Labels: fix 🩹

#1965 feat(codeowners): bg to own *, docs to own docs
  CODEOWNERS
Labels: docs 📝

#1925 Update router terminology
  docs/source/commands/license.mdx
  docs/source/commands/persisted-queries.mdx
  docs/source/commands/supergraphs.mdx
Labels: docs 📝

#1964 fix(docs): add cpu arch to what we collect per command
  docs/source/privacy.mdx
Labels: feature 🎉

#1971 Allow ARM Macs to pull `aarch64` `supergraph` binaries where available
  Cargo.lock
  Cargo.toml
  src/command/install/plugin.rs
Labels: feature 🎉

#1972 chore(ci+deps): Fix up Release CI and Explicitly add `tokio` feature flag
  .circleci/config.yml
  xtask/Cargo.toml
Labels: maintenance 🛠️

#1973 release: v0.24.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  docs/source/ci-cd.mdx
  docs/source/contributing.md
  docs/source/errors.md
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#1980 feature(smokes): Run Smoke Tests on all supported platforms
  .circleci/config.yml
  .github/workflows/run-smokes.yml
  .github/workflows/smoke-test.yml
  .github/workflows/tests-mac-x86.yml
Labels: maintenance 🛠️

#1936 Enable Retries for Transient Errors Connecting to Graphs/Subgraphs
  src/command/dev/do_dev.rs
  src/command/dev/introspect.rs
  src/command/dev/schema.rs
  src/command/dev/watcher.rs
  src/options/subgraph.rs
Labels: feature 🎉

#1984 Add `--graph-ref` flag to `rover dev`
  Cargo.lock
  Cargo.toml
  src/command/dev/do_dev.rs
  src/command/dev/mod.rs
  src/command/dev/protocol/leader.rs
  src/command/dev/remote_subgraphs.rs
Labels: feature 🎉

#1989 Minor Smoke Test Fixes
  .github/workflows/run-smokes-manual.yml
  .github/workflows/smoke-test.yml
Labels: maintenance 🛠️

#1991 release: v0.25.0-rc.0
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  docs/source/ci-cd.mdx
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#1990 Make sure the x86 Mac tests use latest supergraph version
  .circleci/config.yml
  .github/workflows/tests-mac-x86.yml
  xtask/src/commands/github_action.rs
Labels: maintenance 🛠️

#1993 Make brew update again when we run it
  .circleci/config.yml
Labels: maintenance 🛠️

#1945 Adds graph-ref flag to dev subcommand docs
  docs/source/commands/dev.mdx
Labels: docs 📝

#1996 fix(output): Fix regression introduced regarding passing file names to `--output`
  src/options/output.rs
  tests/main.rs
  tests/output/mod.rs
  tests/output/to_file.rs
Labels: fix 🩹

#1997 release: v0.25.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/package-lock.json
  docs/source/ci-cd.mdx
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#1999 Integrate the Smoke Tests Into Integration Test Framework To Allow Easier Extension
  .github/workflows/smoke-test.yml
  Cargo.lock
  Cargo.toml
  tests/e2e/dev.rs
  tests/e2e/mod.rs
  tests/test_e2e.rs
  xtask/src/commands/mod.rs
  xtask/src/commands/smoke.rs
  xtask/src/main.rs
  xtask/src/tools/npm.rs
Labels: maintenance 🛠️

#2002 Add nicer names to GitHub actions workflow
  .github/workflows/run-smokes-manual.yml
  .github/workflows/run-smokes.yml
  .github/workflows/smoke-test.yml
  .github/workflows/tests-mac-x86.yml
Labels: maintenance 🛠️

#2003 Add test for `subgraph introspect`
  .github/workflows/smoke-test.yml
  Cargo.lock
  Cargo.toml
  examples/supergraph-demo/pandas/package.json
  examples/supergraph-demo/pandas/pandas.mjs
  tests/e2e/dev.rs
  tests/e2e/mod.rs
  tests/e2e/subgraph/introspect.rs
  tests/e2e/subgraph/mod.rs
Labels: maintenance 🛠️

#2009 release: v0.26.0-rc.0
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  deny.toml
  docs/source/ci-cd.mdx
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release
