Repository apollographql/rover, pull requests merged in 2024-08, with the labels that each got.

#2001 Add `--graph-ref` to `supergraph compose`
  Cargo.lock
  Cargo.toml
  crates/rover-client/Cargo.toml
  crates/rover-client/src/operations/subgraph/fetch_all/fetch_all_query.graphql
  crates/rover-client/src/operations/subgraph/fetch_all/mod.rs
  crates/rover-client/src/operations/subgraph/fetch_all/runner.rs
  crates/rover-client/src/operations/subgraph/fetch_all/types.rs
  crates/rover-client/src/operations/subgraph/mod.rs
  crates/rover-std/src/emoji.rs
  src/command/dev/do_dev.rs
  src/command/dev/mod.rs
  src/command/dev/remote_subgraphs.rs
  src/command/supergraph/compose/do_compose.rs
  src/command/supergraph/mod.rs
  src/command/supergraph/resolve_config.rs
  src/utils/mod.rs
  src/utils/parsers.rs
  src/utils/supergraph_config.rs
Labels: feature 🎉

#2032 Fix up E2E tests
  .github/workflows/smoke-test.yml
  tests/e2e/install/plugin.rs
  tests/e2e/subgraph/publish.rs
Labels: fix 🩹

#2051 release: v0.26.0-rc.1
  Cargo.lock
  Cargo.toml
  README.md
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  docs/source/ci-cd.mdx
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#2037 Adds --graph-ref to supergraph compose docs
  docs/source/commands/dev.mdx
  docs/source/commands/supergraphs.mdx
Labels: docs 📝

#2065 Allow `rover dev` to utilise watching again
  src/command/dev/do_dev.rs
  src/command/supergraph/compose/do_compose.rs
  src/utils/supergraph_config.rs
Labels: fix 🩹

#2064 release: v0.26.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/package-lock.json
  docs/source/ci-cd.mdx
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#2089 release: v0.26.1-rc.0
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/last_run.uuid
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  docs/source/ci-cd.mdx
  docs/source/getting-started.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release
