Repository apollographql/rover, pull requests merged in 2025-04, with the labels that each got.

#2480 Update openssl and tokio dependencies
  Cargo.lock
  deny.toml
Labels: :christmas_tree: dependencies

#2470 Add prompt for project name with validation for init command
  src/command/init/config.rs
  src/command/init/mod.rs
  src/command/init/states.rs
  src/command/init/tests/transitions_tests.rs
  src/command/init/transitions.rs
  src/options/project_name.rs
Labels: feature 🎉

#2475 feat(init): Add graph_id provisioning step with validation
  Cargo.toml
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  installers/npm/package-lock.json
  src/command/init/config.rs
  src/command/init/graph_id/errors/conversions.rs
  src/command/init/graph_id/errors/mod.rs
  src/command/init/graph_id/generation.rs
  src/command/init/graph_id/mod.rs
  src/command/init/graph_id/utils/mod.rs
  src/command/init/graph_id/utils/random.rs
  src/command/init/graph_id/utils/strings.rs
  src/command/init/graph_id/validation.rs
  src/command/init/helpers.rs
  src/command/init/mod.rs
  src/command/init/states.rs
  src/command/init/tests/transitions_tests.rs
  src/command/mod.rs
  src/options/project_graphid.rs
Labels: feature 🎉

#2495 feat(docs) Adding `configuring` slug to docs link list
  src/command/docs/shortlinks.rs
  src/command/init/helpers.rs
Labels: feature 🎉

#2487 feat(init): Auth support for `init` command
  Cargo.lock
  crates/rover-client/src/operations/config/who_am_i/service.rs
  crates/rover-std/src/lib.rs
  crates/rover-std/src/style.rs
  crates/rover-std/src/symbols.rs
  crates/rover-std/src/url.rs
  src/cli.rs
  src/command/init/graph_id/generation.rs
  src/command/init/helpers.rs
  src/command/init/mod.rs
  src/command/init/states.rs
  src/command/init/transitions.rs
  src/options/mod.rs
  src/options/project_authentication.rs
Labels: feature 🎉

#2509 release: v0.29.0-rc.1
  Cargo.lock
  Cargo.toml
  README.md
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  crates/rover-client/src/shared/lint_response.rs
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#2515 release: v0.29.0-rc.2
  Cargo.lock
  Cargo.toml
  README.md
  crates/rover-client/package-lock.json
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/crates/rover-client/.schema/hash.id
  installers/crates/rover-client/.schema/schema.graphql
  installers/npm/package-lock.json
  installers/npm/package.json
  installers/src/command/template/schema.graphql
Labels: 🚢 release

#2519 release: v0.29.0-rc.3
  Cargo.lock
  Cargo.toml
  README.md
  crates/rover-client/package-lock.json
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#2525 bugfix(init): Update code snippet to run rover dev
  src/command/init/helpers.rs
Labels: feature 🎉

#2527 bugfix(init) Adding check for user api key
  src/command/init/transitions.rs
Labels: feature 🎉, fix 🩹

#2526 docs: `init` command
  docs/source/_sidebar.yaml
  docs/source/commands/init.mdx
Labels: docs 📝

#2528 fix(init): Exit immediately when GraphQL Template is selected
  src/command/init/helpers.rs
  src/command/init/mod.rs
  src/command/init/transitions.rs
Labels: feature 🎉

#2522 release: v0.29.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  docs/source/ci-cd.mdx
  docs/source/getting-started.mdx
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#2533 Fix crash and improve error handling for invalid API keys
  crates/rover-graphql/src/lib.rs
  src/command/config/whoami.rs
  src/command/init/transitions.rs
Labels: bug 🐞

#2529 updating docs for new repos/marketplace listings
  docs/source/ci-cd.mdx
Labels: docs 📝

#2531 docs: add graph ref environment variable info
  docs/source/commands/dev.mdx
  docs/source/configuring.mdx
Labels: docs 📝

#2534 Increase telemetry timeout
  crates/sputnik/src/session.rs
Labels: maintenance 🛠️

#2535 Upgrade to Rust 1.86
  crates/rover-client/src/releases.rs
  installers/binstall/src/install.rs
  rust-toolchain.toml
  src/command/dev/do_dev.rs
  src/composition/supergraph/config/resolver/mod.rs
  src/error/metadata/mod.rs
Labels: :christmas_tree: dependencies

#2538 release: v0.29.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  docs/source/ci-cd.mdx
  docs/source/getting-started.mdx
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#2536 feature(init): Removing `init` feature flag usage
  Cargo.toml
  src/cli.rs
  src/command/init/config.rs
  src/command/init/mod.rs
  src/command/init/options/mod.rs
  src/command/init/options/project_authentication.rs
  src/command/init/options/project_graphid.rs
  src/command/init/options/project_name.rs
  src/command/init/options/project_organization.rs
  src/command/init/options/project_type.rs
  src/command/init/options/project_use_case.rs
  src/command/init/states.rs
  src/command/init/transitions.rs
  src/command/mod.rs
  src/command/output.rs
  src/options/mod.rs
  src/options/template.rs
  tests/e2e/mod.rs
Labels: maintenance 🛠️
