Repository apollographql/rover, pull requests merged in 2025-03, with the labels that each got.

#2437 Replace backoff with backon
  Cargo.lock
  Cargo.toml
  crates/rover-client/Cargo.toml
  crates/rover-client/readme.md
  crates/rover-client/src/blocking/client.rs
  deny.toml
Labels: :christmas_tree: dependencies

#2440 Add exemption for unmaintained humantime dependency
  deny.toml
Labels: maintenance 🛠️

#2442 Better error on missing environment variable
  src/command/dev/router/config/mod.rs
  src/utils/expansion.rs
Labels: fix 🩹

#2444 Update CODEOWNERS to Graph Tooling
  CODEOWNERS
  RELEASE_CHECKLIST.md
Labels: maintenance 🛠️

#2445 Fix telemetry reporting for release builds
  Cargo.toml
  crates/sputnik/src/session.rs
Labels: fix 🩹

#2447 release: v0.28.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/package-lock.json
  docs/source/ci-cd.mdx
  docs/source/getting-started.mdx
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#2443 Adding initial scaffolding for init command behind cargo flag
  Cargo.toml
  src/cli.rs
  src/command/init/mod.rs
  src/command/mod.rs
Labels: feature 🎉

#2448 Fix curl installer anonymized usage collection message
  src/command/install/mod.rs
Labels: maintenance 🛠️

#2462 Adding prompt for project use case to init command
  src/command/init/mod.rs
  src/options/mod.rs
  src/options/project_use_case.rs
Labels: feature 🎉
