Repository apollographql/rover, pull requests merged in 2025-05, with the labels that each got.

#2545 Modifying existing logic to fetch from the new github service latest released version
  crates/rover-client/src/operations/init/github/mod.rs
  crates/rover-client/src/operations/init/mod.rs
  src/command/init/mod.rs
  src/command/init/options/project_use_case.rs
  src/command/init/states.rs
  src/command/init/template_fetcher.rs
  src/command/init/template_operations.rs
  src/command/init/tests/transitions_tests.rs
  src/command/init/transitions.rs
  src/command/template/use.rs
  src/options/mod.rs
  src/options/template.rs
Labels: feature 🎉

#2557 feat(init): Add template selector for "recommended libraries" option
  src/command/init/mod.rs
  src/command/init/options/mod.rs
  src/command/init/options/project_organization.rs
  src/command/init/options/project_template.rs
  src/command/init/states.rs
  src/command/init/template_fetcher.rs
  src/command/init/tests/transitions_tests.rs
  src/command/init/transitions.rs
  src/options/template.rs
Labels: feature 🎉

#2558 feat(rover): Display template commands during `init` flow if one exists
  src/command/init/helpers.rs
  src/command/init/states.rs
  src/command/init/tests/authentication_tests.rs
  src/command/init/tests/mod.rs
  src/command/init/tests/project_authentication_tests.rs
  src/command/init/tests/project_created_message_tests.rs
  src/command/init/transitions.rs
Labels: feature 🎉

#2559 adding start_point_file to specify what file to use in output
  src/command/init/template_fetcher.rs
Labels: feature 🎉

#2560 feat(rover) init flow: make starter file configurable during project creation
  src/command/init/helpers.rs
  src/command/init/states.rs
  src/command/init/tests/project_created_message_tests.rs
  src/command/init/transitions.rs
Labels: feature 🎉

#2562 feat(init): adding `init` flag to default features
  Cargo.toml
  src/command/init/states.rs
  src/command/init/tests/transitions_tests.rs
Labels: feature 🎉

#2563 release: v0.30.0-rc.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  docs/source/errors.md
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#2567 feat(rover): init flow - update project creation copy for accuracy
  src/command/init/template_operations.rs
  src/command/init/transitions.rs
Labels: feature 🎉

#2566 fix(init): Display command in project creation message for typescript template
  src/command/init/helpers.rs
  src/command/init/tests/project_created_message_tests.rs
  src/command/init/transitions.rs
Labels: fix 🩹

#2568 feat(init): Always show template selector for `recommended libraries` flow
  src/command/init/options/project_template.rs
Labels: feature 🎉

#2569 docs: Set the APOLLO_VCS_BRANCH environment variable in GitHub Actions
  docs/source/ci-cd.mdx
Labels: docs 📝

#2571 fix(init) Stripping all non-alphanumeric chars from graph id during generation and adding test
  src/command/init/graph_id/generation.rs
Labels: fix 🩹

#2572 Improving file display in tree mode
  src/command/init/helpers.rs
  src/command/init/states.rs
  src/command/init/template_fetcher.rs
  src/command/init/template_operations.rs
  src/command/init/tests/project_created_message_tests.rs
  src/command/init/tests/transitions_tests.rs
  src/command/init/transitions.rs
Labels: feature 🎉

#2573 feat(rover)init: allow multiple commands to be printed for graph creation message
  src/command/init/helpers.rs
  src/command/init/template_fetcher.rs
  src/command/init/tests/project_created_message_tests.rs
  src/command/init/tests/transitions_tests.rs
  src/command/init/transitions.rs
Labels: feature 🎉

#2579 feat(rover)init: correctly capitalize TypeScript
  src/command/init/template_fetcher.rs
Labels: feature 🎉

#2580 feat(rover)init: Update `Next steps` section in project creation message
  src/command/init/helpers.rs
  src/command/init/tests/project_created_message_tests.rs
Labels: feature 🎉

#2582 feat(init) Moving to using env var vs flag for graph ref when prompting user to run dev command
  src/command/init/helpers.rs
Labels: feature 🎉

#2587 release: 0.30.0-rc.2
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/binstall/src/install.rs
  installers/npm/package-lock.json
  installers/npm/package.json
  src/command/dev/do_dev.rs
Labels: 🚢 release

#2588 release: v0.30.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  crates/rover-std/src/fs.rs
  docs/source/ci-cd.mdx
  docs/source/getting-started.mdx
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
  tests/integration/output/to_file.rs
Labels: 🚢 release

#2561 docs: `rover init` v.30 update
  docs/source/commands/init.mdx
Labels: docs 📝

#2593 release: v0.31.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/package-lock.json
  docs/source/ci-cd.mdx
  docs/source/getting-started.mdx
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#2594 Fix userid in CHANGELOG update
  CHANGELOG.md
Labels: maintenance 🛠️

#2597 chore: removing `init` feature flag
  .github/workflows/run-smokes-on-pr.yml
  Cargo.toml
  src/command/init/helpers.rs
  src/command/init/mod.rs
  src/command/init/options/mod.rs
  src/command/init/options/project_use_case.rs
  src/command/init/states.rs
  src/command/init/template_fetcher.rs
  src/command/init/template_operations.rs
  src/command/init/tests/transitions_tests.rs
  src/command/init/transitions.rs
Labels: maintenance 🛠️

#2596 MCP fixes
  CHANGELOG.md
  src/command/dev/do_dev.rs
  src/command/dev/mcp.rs
  src/command/dev/mcp/binary.rs
  src/command/dev/router/binary.rs
Labels: fix 🩹

#2598 release: v0.31.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  docs/source/ci-cd.mdx
  docs/source/getting-started.mdx
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#2601 Expand supergraph config variables in file watcher
  CHANGELOG.md
  src/composition/watchers/watcher/supergraph_config.rs
Labels: fix 🩹

#2602 release: v0.31.2
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  docs/source/ci-cd.mdx
  docs/source/getting-started.mdx
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#2603 fix(init): Better error handling for graph creation permission errors
  src/command/init/transitions.rs
  src/error/metadata/suggestion.rs
Labels: fix 🩹

#2608 release: v0.31.3
  CHANGELOG.md
  Cargo.lock
  crates/rover-client/package-lock.json
  docs/source/ci-cd.mdx
  docs/source/getting-started.mdx
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#2612 release: v0.32.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/package-lock.json
  docs/source/ci-cd.mdx
  docs/source/getting-started.mdx
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release
