Repository apollographql/rover, pull requests merged in 2025-02, with the labels that each got.

#2385 release: v0.27.0-rc.4
  Cargo.lock
  Cargo.toml
  crates/rover-client/.schema/hash.id
  crates/rover-client/.schema/schema.graphql
  crates/rover-client/package-lock.json
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#2392 release: v0.27.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/package-lock.json
  docs/source/ci-cd.mdx
  docs/source/getting-started.mdx
  installers/binstall/scripts/nix/install.sh
  installers/binstall/scripts/windows/install.ps1
  installers/npm/package-lock.json
  installers/npm/package.json
Labels: 🚢 release

#2333 chore(docs): update for dev rewrite
  docs/source/commands/dev.mdx
Labels: docs 📝

#2413 Replace prettytable-rs with comfy-table
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/rover-client/Cargo.toml
  crates/rover-client/src/shared/check_response.rs
  src/command/check_workflow.rs
  src/command/output.rs
  src/utils/table.rs
Labels: maintenance 🛠️
